### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-795-5f14a5f
client docker - perconalab/pmm-client-fb:PR-795-5f14a5f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-795-5f14a5f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-795-7376a09
client docker - perconalab/pmm-client-fb:PR-795-7376a09
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-795-7376a09.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-795-8f9306b
client docker - perconalab/pmm-client-fb:PR-795-8f9306b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-795-8f9306b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-795-42b03ec
client docker - perconalab/pmm-client-fb:PR-795-42b03ec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-795-42b03ec.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-795-c95af80
client docker - perconalab/pmm-client-fb:PR-795-c95af80
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-795-c95af80.tar.gz

**Comment by BupycHuk** [comment]
@puneet0191 conflicts in PR

**Comment by puneet0191** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/799

**Pull request closed without merging**
