### PR TITLE
PMM-7231 Disable channel

### PR DESCRIPTION
**Pull request by Dasio**
[PMM-7231](https://jira.percona.com/browse/PMM-7231)

pmm-managed  - https://github.com/percona/pmm-managed/pull/669

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1537-0139066
client docker - perconalab/pmm-client-fb:PR-1537-0139066
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-0139066.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1537-0139066&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-0139066.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6062/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5479/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7051/

**Comment by Dasio** [comment]
UI tests failed not related to this PR, can ignore.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1537-889cf82
client docker - perconalab/pmm-client-fb:PR-1537-889cf82
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-889cf82.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1537-889cf82&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-889cf82.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6190/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5607/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7222/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1537-ccbbc76
client docker - perconalab/pmm-client-fb:PR-1537-ccbbc76
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-ccbbc76.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1537-ccbbc76&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-ccbbc76.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6205/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5622/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7237/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1537-192e15b
client docker - perconalab/pmm-client-fb:PR-1537-192e15b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-192e15b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1537-192e15b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-192e15b.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6208/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5625/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7240/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1537-da1c6ea
client docker - perconalab/pmm-client-fb:PR-1537-da1c6ea
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-da1c6ea.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1537-da1c6ea&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-da1c6ea.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1537-da1c6ea
client docker - perconalab/pmm-client-fb:PR-1537-da1c6ea
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-da1c6ea.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1537-da1c6ea&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1537-da1c6ea.tar.gz

**Pull request closed without merging**
