### PR TITLE
Fixing proto

### PR DESCRIPTION
**Pull request by artemgavrilov**
- [ ] https://github.com/percona/pmm/pull/834
- [x] https://github.com/percona-platform/platform/pull/411
- [x] https://github.com/percona-platform/saas/pull/62
- [ ] https://github.com/percona/pmm-managed/pull/1016

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2386-d0d5c90
client docker - perconalab/pmm-client-fb:PR-2386-d0d5c90
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2386-d0d5c90.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2386-d0d5c90&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2386-d0d5c90.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9422/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/12790/

**Comment by artemgavrilov** [comment]
API testa failure is unrelated to provided changes and it seems that UI tests failure too.

**Pull request closed without merging**
