### PR TITLE
PMM-5142: add QAN variables update

### PR DESCRIPTION
**Pull request by lunaticusgreen**
https://github.com/percona/grafana-dashboards/pull/553

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-588-af0fe63
client docker - perconalab/pmm-client-fb:PR-588-af0fe63
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-588-af0fe63.tar.gz

**Comment by puneet0191** [comment]
@lunaticusgreen the UI tests seem to break on QAN, while loading Query details, when the user clicks on a query, could you please check once?

**Comment by lunaticusgreen** [comment]
> @lunaticusgreen the UI tests seem to break on QAN, while loading Query details, when the user clicks on a query, could you please check once?

@puneet0191 When i do manual testing this case works fine, lets wait next build and test results

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-588-bd32c0f
client docker - perconalab/pmm-client-fb:PR-588-bd32c0f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-588-bd32c0f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-588-a44c6ae
client docker - perconalab/pmm-client-fb:PR-588-a44c6ae
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-588-a44c6ae.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-588-c91687d
client docker - perconalab/pmm-client-fb:PR-588-c91687d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-588-c91687d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-588-2c9d449
client docker - perconalab/pmm-client-fb:PR-588-2c9d449
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-588-2c9d449.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-588-7e443ce
client docker - perconalab/pmm-client-fb:PR-588-7e443ce
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-588-7e443ce.tar.gz

**Pull request closed without merging**
