### PR TITLE
[FB] PMM-5645 bump build versions

### PR DESCRIPTION
**Pull request by Sevlin**
Related PR's:
- [pmm-submodules](https://github.com/Percona-Lab/pmm-submodules/pull/931) - specs permissions fix
- [pmm-server-packaging](https://github.com/percona/pmm-server-packaging/pull/142/)

### CODE REVIEW

**Comment by AlekSi** [comment]
Should we do something else for pmm2-client rebuilding?

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-926-e706f5c
client docker - perconalab/pmm-client-fb:PR-926-e706f5c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-926-e706f5c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-926-e706f5c
client docker - perconalab/pmm-client-fb:PR-926-e706f5c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-926-e706f5c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-926-51896b2
client docker - perconalab/pmm-client-fb:PR-926-51896b2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-926-51896b2.tar.gz

**Comment by Sevlin** [comment]
@AlekSi these changes are in upstream (both **master** and **PMM-2.0** branches). I'll just revert them for this PR.

**Comment by AlekSi** [comment]
There no changes in this FB anymore?

**Comment by AlekSi** [comment]
7 days ago I asked this question: https://github.com/Percona-Lab/pmm-submodules/pull/926#issuecomment-653068675
In responce to it, you made some changes that are not merged into PMM-2.0. For example, there was a change with `export FORCE=1` or something that is not present anymore.
You force-push removed those commits.
Please stop immediately and recover those commits.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-926-9a4390f
client docker - perconalab/pmm-client-fb:PR-926-9a4390f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-926-9a4390f.tar.gz

**Comment by Sevlin** [comment]
@AlekSi First of all, `export FORCE_BUILD=1` was temporary change to ensure that all packages are rebuild using new Golang version, and we doesn't use **FORCE_BUILD** in production. Second change was permissions fix in build script and megred as [separate PR](https://github.com/Percona-Lab/pmm-submodules/pull/931).

**Comment by AlekSi** [comment]
> There are no changes in this FB anymore?

**Comment by Sevlin** [comment]
> > There are no changes in this FB anymore?

All of the changes are in the description of this FB.
**pmm-server-packaging**: https://github.com/percona/pmm-server-packaging/pull/142/
**pmm-submodules**: https://github.com/Percona-Lab/pmm-submodules/pull/931

**Comment by AlekSi** [comment]
And both are merged. So what you want to me to review?

**Pull request closed without merging**
