### PR TITLE
PMM-12359 added podman setup to FB

### PR DESCRIPTION
**Pull request by vyarosh**
https://jira.percona.com/browse/PMM-12359

### CODE REVIEW

**Comment by vyarosh** [comment]
As a base step podman setup test runner has been added. 
Changing user password and check metrics test has been added to FB check: https://github.com/Percona-Lab/pmm-submodules/actions/runs/5729481751/job/15526278288

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3351-3a7b962
client docker - perconalab/pmm-client-fb:PR-3351-3a7b962
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3351-3a7b962.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3351-3a7b962&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3351-3a7b962.tar.gz

**Comment by vyarosh** [comment]
https://github.com/Percona-Lab/pmm-submodules/actions/runs/5737518133/job/15549316838

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3351-ae0e26b
client docker - perconalab/pmm-client-fb:PR-3351-ae0e26b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3351-ae0e26b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3351-ae0e26b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3351-ae0e26b.tar.gz

**Review by yurkovychv — APPROVED** [review]

**Pull request merged**
