### PR TITLE
PMM-7 Remove yml components

### PR DESCRIPTION
**Pull request by ademidoff**
https://jira.percona.com/browse/PMM-7

This PR:

- removes `component` from `ci-default.yml`
- fixes the wording in several files
- fixes a bug where `trigger` was not listed as a `make` target
- fixes a number of inconsistencies in README
- cleans up `ci.py` a tiny bit
- bumps up `pyaml` dependency

### CODE REVIEW

**Comment by JNKPercona** [comment]
Server docker: perconalab/pmm-server-fb:PR-3769-e31b6bc
Client docker: perconalab/pmm-client-fb:PR-3769-e31b6bc
Client tarball: https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3769-e31b6bc.tar.gz
Staging instance: https://pmm.cd.percona.com/job/pmm3-aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3769-e31b6bc&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3769-e31b6bc.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed: https://pmm.cd.percona.com/job/pmm3-api-tests/1480/

**Review by BupycHuk — APPROVED** [review]

**Review by talhabinrizwan — APPROVED** [review]

**Comment by JNKPercona** [comment]
Server docker: perconalab/pmm-server-fb:PR-3769-26a29ee
Client docker: perconalab/pmm-client-fb:PR-3769-26a29ee
Client tarball: https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3769-26a29ee.tar.gz
Staging instance: https://pmm.cd.percona.com/job/pmm3-aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3769-26a29ee&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3769-26a29ee.tar.gz

**Comment by JNKPercona** [comment]
API tests have succeded: https://pmm.cd.percona.com/job/pmm3-api-tests/1485/

**Pull request merged**
