### PR TITLE
PMM-5003 Fix agent, service, node types values.

### PR DESCRIPTION
**Pull request by BupycHuk**
https://github.com/percona/pmm-admin/pull/84

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-721-463f968
client docker - perconalab/pmm-client-fb:PR-721-463f968
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-721-463f968.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-721-708b76e
client docker - perconalab/pmm-client-fb:PR-721-708b76e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-721-708b76e.tar.gz

**Comment by AlekSi** [comment]
@BupycHuk Please reset to the current PMM-2.0 to pull Prometheus-related fixes.

**Comment by BupycHuk** [comment]
@AlekSi I checked commits since my PR is created in this repo and there are no commits changed anything in this repo itself, only in submodules. So rewinding submodules will have the same effect as resetting.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-721-4830109
client docker - perconalab/pmm-client-fb:PR-721-4830109
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-721-4830109.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-721-10c300f
client docker - perconalab/pmm-client-fb:PR-721-10c300f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-721-10c300f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-721-36ff5dc
client docker - perconalab/pmm-client-fb:PR-721-36ff5dc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-721-36ff5dc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-721-70639a1
client docker - perconalab/pmm-client-fb:PR-721-70639a1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-721-70639a1.tar.gz

**Pull request closed without merging**
