### PR TITLE
PMM-2319 Grafana 5.0.4

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-24-ea9f728
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-24-ea9f728.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-24-ea9f728
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-24-ea9f728.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-24-ea9f728
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-24-ea9f728.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-24-ea9f728
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-24-ea9f728.tar.gz

**Comment by rnovikovP** [comment]
Merged to master

**Pull request closed without merging**
