### PR TITLE
PMM-12547 BM should not allow taking backups for single node mongodb

### PR DESCRIPTION
**Pull request by ademidoff**
https://jira.percona.com/browse/PMM-12547

- https://github.com/percona/pmm/pull/2508
- https://github.com/percona-platform/grafana/pull/689

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3399-71f7aed
client docker - perconalab/pmm-client-fb:PR-3399-71f7aed
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-71f7aed.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3399-71f7aed&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-71f7aed.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14242/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3399-4fd74da
client docker - perconalab/pmm-client-fb:PR-3399-4fd74da
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-4fd74da.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3399-4fd74da&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-4fd74da.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14243/

**Comment by ademidoff** [comment]
> API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14243/

The tests were fixed - https://pmm.cd.percona.com/job/pmm2-api-tests/14245/console

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3399-ed2f3ec
client docker - perconalab/pmm-client-fb:PR-3399-ed2f3ec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-ed2f3ec.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3399-ed2f3ec&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-ed2f3ec.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14246/

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/2508

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3399-cc34391
client docker - perconalab/pmm-client-fb:PR-3399-cc34391
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-cc34391.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3399-cc34391&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3399-cc34391.tar.gz

**Pull request closed without merging**
