### PR TITLE
SAAS-153 check panel viewer access message

### PR DESCRIPTION
**Pull request by atymchuk**
- [ ] https://github.com/percona/grafana-dashboards/pull/747

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-872-d371f8a
client docker - perconalab/pmm-client-fb:PR-872-d371f8a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-872-d371f8a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-872-ef1991b
client docker - perconalab/pmm-client-fb:PR-872-ef1991b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-872-ef1991b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-872-7c14b9d
client docker - perconalab/pmm-client-fb:PR-872-7c14b9d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-872-7c14b9d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-872-35d8db2
client docker - perconalab/pmm-client-fb:PR-872-35d8db2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-872-35d8db2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-872-a95e995
client docker - perconalab/pmm-client-fb:PR-872-a95e995
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-872-a95e995.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-872-f515d96
client docker - perconalab/pmm-client-fb:PR-872-f515d96
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-872-f515d96.tar.gz

**Comment by atymchuk** [comment]
Done, closing.

**Pull request closed without merging**
