### PR TITLE
PMM-4919 Re-register force allows new hostname.

### PR DESCRIPTION
**Pull request by AlekSi**
- [ ] https://github.com/percona/pmm-managed/pull/309
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/70

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-d98bf8b
client docker - perconalab/pmm-client-fb:PR-661-d98bf8b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-d98bf8b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-cce38a5
client docker - perconalab/pmm-client-fb:PR-661-cce38a5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-cce38a5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-e269286
client docker - perconalab/pmm-client-fb:PR-661-e269286
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-e269286.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-794c07b
client docker - perconalab/pmm-client-fb:PR-661-794c07b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-794c07b.tar.gz

**Comment by BupycHuk** [comment]
@percona-csalguero could you create new pmm-submodules branch from up-to date PMM-2.0 branch, please.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-889e1a5
client docker - perconalab/pmm-client-fb:PR-661-889e1a5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-889e1a5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-3b2a03f
client docker - perconalab/pmm-client-fb:PR-661-3b2a03f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-3b2a03f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-3b2a03f
client docker - perconalab/pmm-client-fb:PR-661-3b2a03f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-3b2a03f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-3b2a03f
client docker - perconalab/pmm-client-fb:PR-661-3b2a03f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-3b2a03f.tar.gz

**Comment by AlekSi** [comment]
@BupycHuk 
```
settings_test.go:32: 
Error Trace:	settings_test.go:32
Error:      	Not equal: 
            	expected: &server.GetSettingsOKBodySettingsMetricsResolutions{Hr:"5s", Mr:"5s", Lr:"60s"}
            	actual  : &server.GetSettingsOKBodySettingsMetricsResolutions{Hr:"5s", Mr:"10s", Lr:"60s"}
            	
            	Diff:
            	--- Expected
            	+++ Actual
            	@@ -2,3 +2,3 @@
            	  Hr: (string) (len=2) "5s",
            	- Mr: (string) (len=2) "5s",
            	+ Mr: (string) (len=3) "10s",
            	  Lr: (string) (len=3) "60s"
Test:       	TestSettings/GetSettings
```

❓

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-661-fcd8e13
client docker - perconalab/pmm-client-fb:PR-661-fcd8e13
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-661-fcd8e13.tar.gz

**Comment by BupycHuk** [comment]
@AlekSi tests are fixed :)

**Pull request closed without merging**
