### PR TITLE
PMM-4620 Fix high CPU usage in MongoDB profiler.

### PR DESCRIPTION
**Pull request by BupycHuk**
- [ ] https://github.com/percona/pmm-agent/pull/142

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-0cd9455
client docker - perconalab/pmm-client-fb:PR-599-0cd9455
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-0cd9455.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-75a44e1
client docker - perconalab/pmm-client-fb:PR-599-75a44e1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-75a44e1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-d599a58
client docker - perconalab/pmm-client-fb:PR-599-d599a58
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-d599a58.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-4e6688e
client docker - perconalab/pmm-client-fb:PR-599-4e6688e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-4e6688e.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-c10928f
client docker - perconalab/pmm-client-fb:PR-599-c10928f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-c10928f.tar.gz

**Comment by AlekSi** [comment]
Rebased to set the correct version.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-e96a2e7
client docker - perconalab/pmm-client-fb:PR-599-e96a2e7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-e96a2e7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-599-d630fca
client docker - perconalab/pmm-client-fb:PR-599-d630fca
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-599-d630fca.tar.gz

**Pull request closed without merging**
