### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by denisok** [comment]
maybe 2.16? we wouldn't stand another patch release...

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1619-a2cf3f3
client docker - perconalab/pmm-client-fb:PR-1619-a2cf3f3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1619-a2cf3f3.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1619-a2cf3f3&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1619-a2cf3f3.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6384/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7433/

**Comment by rnovikovP** [comment]
considering current merges with 2.16  code  .. this PR  is  not needed

**Pull request closed without merging**
