### PR TITLE
[FB] PMM-6234 prometheus 2.19.2

### PR DESCRIPTION
**Pull request by Sevlin**
Related PRs:
- [pmm-server-packaging](https://github.com/percona/pmm-server-packaging/pull/148)

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-974-00c488d
client docker - perconalab/pmm-client-fb:PR-974-00c488d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-974-00c488d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-974-ca29496
client docker - perconalab/pmm-client-fb:PR-974-ca29496
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-974-ca29496.tar.gz

**Comment by AlekSi** [comment]
@alexanderblinkov-percona Someone from backend team should run pmm-managed tests with PMM Server container from that FB: https://github.com/percona/pmm-managed/blob/22524d05feea287a2d315df3e5c2f557242ef9e4/docker-compose.yml#L5

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-974-9277911
client docker - perconalab/pmm-client-fb:PR-974-9277911
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-974-9277911.tar.gz

**Comment by BupycHuk** [comment]
@EvgeniyPatlan shouldn't it be closed?

**Pull request closed without merging**
