### PR TITLE
PMM-3089 Restore qan-agent config.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-164-3c65223
client docker - perconalab/pmm-client-fb:PR-164-3c65223
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-164-3c65223.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-164-3c65223
client docker - perconalab/pmm-client-fb:PR-164-3c65223
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-164-3c65223.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-164-9730987
client docker - perconalab/pmm-client-fb:PR-164-9730987
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-164-9730987.tar.gz

**Comment by AlekSi** [comment]
@askomorokhov Please if there is something useful.

**Pull request closed without merging**
