### PR TITLE
PMM-7085 DBaaS dashboard showing when feature flag not enabled

### PR DESCRIPTION
**Pull request by adivinho**
- [ ] https://github.com/percona/pmm-server/pull/240

- [ ] https://github.com/percona/pmm-server-packaging/pull/188

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-e718a20
client docker - perconalab/pmm-client-fb:PR-1326-e718a20
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-e718a20.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-e718a20&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-e718a20.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5215/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4616/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5930/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-bba8f23
client docker - perconalab/pmm-client-fb:PR-1326-bba8f23
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-bba8f23.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-bba8f23&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-bba8f23.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5226/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4627/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5942/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-c79893e
client docker - perconalab/pmm-client-fb:PR-1326-c79893e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c79893e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-c79893e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c79893e.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5240/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4641/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5958/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-d543a43
client docker - perconalab/pmm-client-fb:PR-1326-d543a43
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-d543a43.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-d543a43&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-d543a43.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5288/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4691/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6016/

**Comment by puneet0191** [comment]
@adivinho the UI tests are failing because even after passing the env variable the dashboards is not available, could you please check

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-1963502
client docker - perconalab/pmm-client-fb:PR-1326-1963502
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-1963502.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-1963502&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-1963502.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-1963502
client docker - perconalab/pmm-client-fb:PR-1326-1963502
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-1963502.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-1963502&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-1963502.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5296/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4699/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6029/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-0da85a0
client docker - perconalab/pmm-client-fb:PR-1326-0da85a0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-0da85a0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-0da85a0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-0da85a0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-5c72e11
client docker - perconalab/pmm-client-fb:PR-1326-5c72e11
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-5c72e11.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-5c72e11&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-5c72e11.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-ef14715
client docker - perconalab/pmm-client-fb:PR-1326-ef14715
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-ef14715.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-ef14715&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-ef14715.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-c37619e
client docker - perconalab/pmm-client-fb:PR-1326-c37619e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c37619e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-c37619e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c37619e.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-c37619e
client docker - perconalab/pmm-client-fb:PR-1326-c37619e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c37619e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-c37619e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c37619e.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-c37619e
client docker - perconalab/pmm-client-fb:PR-1326-c37619e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c37619e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-c37619e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c37619e.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5371/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4776/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6142/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-75c82cb
client docker - perconalab/pmm-client-fb:PR-1326-75c82cb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-75c82cb.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-75c82cb&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-75c82cb.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-186b7a3
client docker - perconalab/pmm-client-fb:PR-1326-186b7a3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-186b7a3.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-186b7a3&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-186b7a3.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5392/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4797/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6170/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-6e12bb2
client docker - perconalab/pmm-client-fb:PR-1326-6e12bb2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-6e12bb2.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-6e12bb2&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-6e12bb2.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5400/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4806/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6179/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-c13591a
client docker - perconalab/pmm-client-fb:PR-1326-c13591a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c13591a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-c13591a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c13591a.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5403/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4809/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6182/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1326-c13591a
client docker - perconalab/pmm-client-fb:PR-1326-c13591a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c13591a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1326-c13591a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1326-c13591a.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5650/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5060/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6523/

**Pull request closed without merging**
