### PR TITLE
PMM-6389 Add VictoriaMetrics

### PR DESCRIPTION
**Pull request by valyala**
- [ ] https://github.com/Percona-Lab/percona-images/pull/86
- [ ] https://github.com/percona/pmm-update/pull/96
- [ ] https://github.com/percona/pmm-managed/pull/455

https://github.com/Percona-Lab/pmm-submodules/pull/1020

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-f22a75c
client docker - perconalab/pmm-client-fb:PR-1020-f22a75c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-f22a75c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-6e14fe5
client docker - perconalab/pmm-client-fb:PR-1020-6e14fe5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-6e14fe5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-f9bb416
client docker - perconalab/pmm-client-fb:PR-1020-f9bb416
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-f9bb416.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-a35c1d0
client docker - perconalab/pmm-client-fb:PR-1020-a35c1d0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-a35c1d0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-a35c1d0
client docker - perconalab/pmm-client-fb:PR-1020-a35c1d0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-a35c1d0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-a35c1d0
client docker - perconalab/pmm-client-fb:PR-1020-a35c1d0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-a35c1d0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-c0737e8
client docker - perconalab/pmm-client-fb:PR-1020-c0737e8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-c0737e8.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-ec23035
client docker - perconalab/pmm-client-fb:PR-1020-ec23035
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-ec23035.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-022ebe2
client docker - perconalab/pmm-client-fb:PR-1020-022ebe2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-022ebe2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-5350263
client docker - perconalab/pmm-client-fb:PR-1020-5350263
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-5350263.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-bbdef47
client docker - perconalab/pmm-client-fb:PR-1020-bbdef47
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-bbdef47.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-3daff10
client docker - perconalab/pmm-client-fb:PR-1020-3daff10
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-3daff10.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-98b67c5
client docker - perconalab/pmm-client-fb:PR-1020-98b67c5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-98b67c5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-1881f3f
client docker - perconalab/pmm-client-fb:PR-1020-1881f3f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-1881f3f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-3d69cc0
client docker - perconalab/pmm-client-fb:PR-1020-3d69cc0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-3d69cc0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-8aea0c0
client docker - perconalab/pmm-client-fb:PR-1020-8aea0c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-8aea0c0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-0f394cf
client docker - perconalab/pmm-client-fb:PR-1020-0f394cf
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-0f394cf.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-1a8e2cd
client docker - perconalab/pmm-client-fb:PR-1020-1a8e2cd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-1a8e2cd.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-5089a0a
client docker - perconalab/pmm-client-fb:PR-1020-5089a0a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-5089a0a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-d570c89
client docker - perconalab/pmm-client-fb:PR-1020-d570c89
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-d570c89.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-b44185b
client docker - perconalab/pmm-client-fb:PR-1020-b44185b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-b44185b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-9aee0ba
client docker - perconalab/pmm-client-fb:PR-1020-9aee0ba
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-9aee0ba.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-9290b66
client docker - perconalab/pmm-client-fb:PR-1020-9290b66
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-9290b66.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-e9bec80
client docker - perconalab/pmm-client-fb:PR-1020-e9bec80
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-e9bec80.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-59f3206
client docker - perconalab/pmm-client-fb:PR-1020-59f3206
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-59f3206.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-cc6adc0
client docker - perconalab/pmm-client-fb:PR-1020-cc6adc0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-cc6adc0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-92d4a20
client docker - perconalab/pmm-client-fb:PR-1020-92d4a20
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-92d4a20.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-cca0fdb
client docker - perconalab/pmm-client-fb:PR-1020-cca0fdb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-cca0fdb.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1020-5246288
client docker - perconalab/pmm-client-fb:PR-1020-5246288
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1020-5246288.tar.gz

**Comment by AlekSi** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/1111

**Pull request closed without merging**
