### PR TITLE
PMM-6457 API db cluster.

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-6457

ref:
- https://github.com/Percona-Lab/pmm-api-tests/pull/125
- https://github.com/percona-platform/dbaas-controller/pull/58
- https://github.com/percona/pmm-managed/pull/468
- https://github.com/percona/pmm/pull/582

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1124-8f30ce1
client docker - perconalab/pmm-client-fb:PR-1124-8f30ce1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1124-8f30ce1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1124-9a4fa9d
client docker - perconalab/pmm-client-fb:PR-1124-9a4fa9d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1124-9a4fa9d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1124-bcd135a
client docker - perconalab/pmm-client-fb:PR-1124-bcd135a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1124-bcd135a.tar.gz

**Comment by BupycHuk** [comment]
Use this FB https://github.com/Percona-Lab/pmm-submodules/pull/1142

**Pull request closed without merging**
