### PR TITLE
PMM-6816 mongoDB exporter v2 release - 0.20.1

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1262-33e4b8b
client docker - perconalab/pmm-client-fb:PR-1262-33e4b8b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1262-33e4b8b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1262-33e4b8b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1262-33e4b8b.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5039/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4421/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5736/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1262-106760b
client docker - perconalab/pmm-client-fb:PR-1262-106760b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1262-106760b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1262-106760b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1262-106760b.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5069/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4451/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5776/

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
