### PR TITLE
PMM-9648-upgrade-singlestat-panels-to-stat (FB)

### PR DESCRIPTION
**Pull request by anton-bystrov**
Custom branches: 
grafana-dashboards

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2390-ae643d0
client docker - perconalab/pmm-client-fb:PR-2390-ae643d0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2390-ae643d0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2390-ae643d0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2390-ae643d0.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9433/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/12828/

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/grafana-dashboards/pull/1319

**Comment by puneet0191** [comment]
@anton-bystrov update your FB

**Pull request closed without merging**
