### PR TITLE
ci: minor readme updates

### PR DESCRIPTION
**Pull request by ademidoff**

### CODE REVIEW

**Comment by ademidoff** [comment]
@nikita-b I realized we can make docs a bit better :)
Maybe we should consider explaining all `ci.py` commands in detail?

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1997-15a017d
client docker - perconalab/pmm-client-fb:PR-1997-15a017d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1997-15a017d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1997-15a017d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1997-15a017d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7846/

**Review by nikita-b — APPROVED** [review]

**Comment by nikita-b** [comment]
> @nikita-b I realized we can make docs a bit better :)
> Maybe we should consider explaining all `ci.py` commands in detail?

I think we can more details to `--help` option. I'll do it in the next PR.

**Pull request merged**
