### PR TITLE
PMM-9459 Feature build

### PR DESCRIPTION
**Pull request by floatinginbits**
Feature build for [PMM-9459](https://jira.percona.com/browse/PMM-9459)

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2380-f84e201
client docker - perconalab/pmm-client-fb:PR-2380-f84e201
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2380-f84e201.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2380-f84e201&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2380-f84e201.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9407/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/12748/

**Comment by floatinginbits** [comment]
FB testing is done.

**Pull request closed without merging**
