### PR TITLE
PMM-6689 Statements problem with PG13.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**

### CODE REVIEW

**Comment by JiriCtvrtka** [comment]
PR: https://github.com/percona/pmm-agent/pull/193

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1168-00517d3
client docker - perconalab/pmm-client-fb:PR-1168-00517d3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1168-00517d3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1168-eea17de
client docker - perconalab/pmm-client-fb:PR-1168-eea17de
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1168-eea17de.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4564/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3942/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5138/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4566/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3944/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5141/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1168-5917ca3
client docker - perconalab/pmm-client-fb:PR-1168-5917ca3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1168-5917ca3.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4570/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3948/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5146/

**Pull request closed without merging**
