### PR TITLE
WIP PMM-2472 tmp3

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-70-6c006c5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-70-6c006c5.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-70-6c006c5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-70-6c006c5.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-70-6c006c5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-70-6c006c5.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/qan-app/pull/115 merged
https://github.com/percona/grafana-dashboards/pull/211 merged

**Pull request closed without merging**
