### PR TITLE
PMM-3905 Upstream changes in PostgreSQL.

### PR DESCRIPTION
**Pull request by DexterHD**
Related PRs: 
- https://github.com/percona/pmm-managed/pull/229 
- https://github.com/percona/postgres_exporter/pull/9

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-344-aed3db8
client docker - perconalab/pmm-client-fb:PR-344-aed3db8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-344-aed3db8.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-344-445c662
client docker - perconalab/pmm-client-fb:PR-344-445c662
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-344-445c662.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-344-cb42bb1
client docker - perconalab/pmm-client-fb:PR-344-cb42bb1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-344-cb42bb1.tar.gz

**Comment by DexterHD** [comment]
I'm Closing it because it was merged to master.

**Pull request closed without merging**
