### PR TITLE
PMM-2651 Monitoring directory sizes with the Textfile Collector

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-57-25252a6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-57-25252a6.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-57-25252a6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-57-25252a6.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-57-25252a6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-57-25252a6.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-57-cfcbdf0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-57-cfcbdf0.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-57-74e4c8e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-57-74e4c8e.tar.gz

**Comment by rnovikovP** [comment]
related  PR  https://github.com/percona/grafana-dashboards/pull/206 and  https://github.com/percona/pmm-client/pull/149

**Pull request closed without merging**
