### PR TITLE
PMM-7294: pagination

### PR DESCRIPTION
**Pull request by fabio-silva**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1484-ec2cf8c
client docker - perconalab/pmm-client-fb:PR-1484-ec2cf8c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-ec2cf8c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1484-ec2cf8c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-ec2cf8c.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5843/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5260/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6761/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1484-4cc8779
client docker - perconalab/pmm-client-fb:PR-1484-4cc8779
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-4cc8779.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1484-4cc8779&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-4cc8779.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5848/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5265/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6769/

**Comment by yurkovychv** [comment]
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/6783/tests - UI tests are passing

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1484-6d7458a
client docker - perconalab/pmm-client-fb:PR-1484-6d7458a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-6d7458a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1484-6d7458a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-6d7458a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1484-28ab271
client docker - perconalab/pmm-client-fb:PR-1484-28ab271
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-28ab271.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1484-28ab271&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1484-28ab271.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5891/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5308/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6823/

**Pull request closed without merging**
