### PR TITLE
PMM-7561 Fix getting logs of wainting containers

### PR DESCRIPTION
**Pull request by jprukner**
https://jira.percona.com/browse/PMM-7561

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1543-74add48
client docker - perconalab/pmm-client-fb:PR-1543-74add48
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-74add48.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1543-74add48&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-74add48.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1543-3999265
client docker - perconalab/pmm-client-fb:PR-1543-3999265
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-3999265.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1543-3999265&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-3999265.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6143/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5560/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7161/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1543-31fc6d6
client docker - perconalab/pmm-client-fb:PR-1543-31fc6d6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-31fc6d6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1543-31fc6d6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-31fc6d6.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6147/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5564/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7165/

**Comment by jprukner** [comment]
Tests are failing because of https://perconacorp.slack.com/archives/G2HEW592P/p1614168340061200

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1543-9d603ff
client docker - perconalab/pmm-client-fb:PR-1543-9d603ff
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-9d603ff.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1543-9d603ff&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1543-9d603ff.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6159/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5576/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7183/

**Comment by yurkovychv** [comment]
please ignore [this](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7183/tests/) failing test

**Pull request closed without merging**
