### PR TITLE
PMM-7379 Alert Rule name edit

### PR DESCRIPTION
**Pull request by Dasio**
[PMM-7379](https://jira.percona.com/browse/PMM-7379)

- [ ] Links to other linked pull requests (optional)
PMM Managed - https://github.com/percona/pmm-managed/pull/678.
API - https://github.com/percona/pmm/pull/692

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1549-2c13bc0
client docker - perconalab/pmm-client-fb:PR-1549-2c13bc0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1549-2c13bc0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1549-2c13bc0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1549-2c13bc0.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6139/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5556/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7154/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1549-18d139f
client docker - perconalab/pmm-client-fb:PR-1549-18d139f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1549-18d139f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1549-18d139f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1549-18d139f.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6145/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5562/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7163/

**Comment by Dasio** [comment]
You can ignore failed API tests. Not related to this PR.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1549-18d139f
client docker - perconalab/pmm-client-fb:PR-1549-18d139f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1549-18d139f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1549-18d139f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1549-18d139f.tar.gz

**Pull request closed without merging**
