### PR TITLE
PMM-2432: Configurable MySQL Slow Log File Rotation.

### PR DESCRIPTION
**Pull request by arvenil**
```bash
#!/usr/bin/env bash
INSTANCE_UUID="7e959bbfc42140fa5604b2ab1e3f9877"
AGENT_UUID="c449d721e72846e476ad901428362cc2"

DATA=$(jq -n --arg INSTANCE_UUID "$INSTANCE_UUID" '{
    UUID: $INSTANCE_UUID
}')

DATA_BASE64=$(echo $DATA | base64)

CMD=$(jq -n --arg DATA_BASE64 "$DATA_BASE64" --arg AGENT_UUID "$AGENT_UUID" '{
 AgentUUID: $AGENT_UUID,
 Service:   "agent",
 Cmd:       "GetDefaults",
 Data:      $DATA_BASE64
}')

curl \
 --silent \
 -H "Content-Type: application/json" \
 -X PUT \
 -d "${CMD}" \
 "http://localhost/qan-api/agents/${AGENT_UUID}/cmd" \
 | jq -r '.Data' \
 | base64 --decode \
 | jq
```

```
{
  "agent": {
    "KeepAlive": 76,
    "Listen": "127.0.0.1:9000"
  },
  "bin": {
    "basedir": "/usr/local/percona/qan-agent"
  },
  "data": {
    "DataEncoding": "gzip",
    "MaxAge": 86400,
    "MaxFiles": 1000,
    "MaxSize": 104857600,
    "SendInterval": 63
  },
  "log": {
    "LogLevel": "warning"
  },
  "qan": {
    "CollectFrom": "slowlog",
    "ExampleQueries": true,
    "Interval": 60,
    "LogOutput": "FILE",
    "LogQueriesNotUsingIndexes": false,
    "LogSlowAdminStatements": false,
    "LogSlowFilter": "",
    "LogSlowRateLimit": 1,
    "LogSlowRateType": "session",
    "LogSlowSlaveStatements": false,
    "LogSlowSpStatements": {},
    "LogSlowVerbosity": "",
    "LogThrottleQueriesNotUsingIndexes": 0,
    "LogTimestamps": null,
    "LongQueryTime": 10,
    "MaxSlowLogSize": 1073741824,
    "MinExaminedRowLimit": 0,
    "PerformanceSchema": true,
    "PerformanceSchemaDigestsSize": 10000,
    "PerformanceSchemaMaxDigestLength": 1024,
    "ReportLimit": 200,
    "RetainSlowLogs": 100,
    "SlowLogRotation": true,
    "SlowQueryLog": true,
    "SlowQueryLogAlwaysWriteTime": 10,
    "SlowQueryLogFile": "/var/lib/mysql/ubuntu-xenial-slow.log",
    "SlowQueryLogUseGlobalControl": "",
    "WorkerRunTime": 55
  }
}
```
```
    "SlowLogRotation": true,
    "RetainSlowLogs": 100,
```

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-a2a442d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-a2a442d.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-0b325ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-0b325ad.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-0b325ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-0b325ad.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-24cbcf6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-24cbcf6.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-5cb1acd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-5cb1acd.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-2567537
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-2567537.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-ee3344a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-ee3344a.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-8d4fb38
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-8d4fb38.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-32-7734c5f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-32-7734c5f.tar.gz

**Comment by rnovikovP** [comment]
ALL Branches  merged to mastrer

**Pull request closed without merging**
