### PR TITLE
removed enabled-alerting docker env var

### PR DESCRIPTION
**Pull request by yurkovychv**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1463-bdee9d4
client docker - perconalab/pmm-client-fb:PR-1463-bdee9d4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1463-bdee9d4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1463-bdee9d4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1463-bdee9d4.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5764/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5179/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6664/

**Review by puneet0191 — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1463-bdee9d4
client docker - perconalab/pmm-client-fb:PR-1463-bdee9d4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1463-bdee9d4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1463-bdee9d4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1463-bdee9d4.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5836/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5253/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6750/

**Pull request closed without merging**
