### PR TITLE
SAAS-236 Refactor Alertmanager

### PR DESCRIPTION
**Pull request by palash25**
[Jira Ticket](https://jira.percona.com/browse/SAAS-236)

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-983-2114ef6
client docker - perconalab/pmm-client-fb:PR-983-2114ef6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-983-2114ef6.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-983-c9319c6
client docker - perconalab/pmm-client-fb:PR-983-c9319c6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-983-c9319c6.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-983-db87f39
client docker - perconalab/pmm-client-fb:PR-983-db87f39
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-983-db87f39.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-983-4159c39
client docker - perconalab/pmm-client-fb:PR-983-4159c39
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-983-4159c39.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-983-6ee122d
client docker - perconalab/pmm-client-fb:PR-983-6ee122d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-983-6ee122d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-983-07bafca
client docker - perconalab/pmm-client-fb:PR-983-07bafca
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-983-07bafca.tar.gz

**Comment by palash25** [comment]
cant seem to resolve the conflicts will reopen a fresh PR

**Pull request closed without merging**
