### PR TITLE
PMM-3705 fix version in rpms

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-2a92138
client docker - perconalab/pmm-client-fb:PR-262-2a92138
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-2a92138.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-9657114
client docker - perconalab/pmm-client-fb:PR-262-9657114
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-9657114.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-a6c8f8a
client docker - perconalab/pmm-client-fb:PR-262-a6c8f8a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-a6c8f8a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-a9721c0
client docker - perconalab/pmm-client-fb:PR-262-a9721c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-a9721c0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-4483582
client docker - perconalab/pmm-client-fb:PR-262-4483582
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-4483582.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-196724c
client docker - perconalab/pmm-client-fb:PR-262-196724c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-196724c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-ec88a55
client docker - perconalab/pmm-client-fb:PR-262-ec88a55
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-ec88a55.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-5278459
client docker - perconalab/pmm-client-fb:PR-262-5278459
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-5278459.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-ac9fc41
client docker - perconalab/pmm-client-fb:PR-262-ac9fc41
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-ac9fc41.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-23d4ae1
client docker - perconalab/pmm-client-fb:PR-262-23d4ae1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-23d4ae1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-e4d2fab
client docker - perconalab/pmm-client-fb:PR-262-e4d2fab
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-e4d2fab.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-cae2457
client docker - perconalab/pmm-client-fb:PR-262-cae2457
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-cae2457.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-6dbf8a4
client docker - perconalab/pmm-client-fb:PR-262-6dbf8a4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-6dbf8a4.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-6dbf8a4
client docker - perconalab/pmm-client-fb:PR-262-6dbf8a4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-6dbf8a4.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-6dbf8a4
client docker - perconalab/pmm-client-fb:PR-262-6dbf8a4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-6dbf8a4.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-262-6dbf8a4
client docker - perconalab/pmm-client-fb:PR-262-6dbf8a4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-262-6dbf8a4.tar.gz

**Comment by AlekSi** [comment]
@hors Should that one be closed and deleted?

**Pull request closed without merging**
