### PR TITLE
PMM-7653 mongodb_exporter 0.20.3, pmm 2.15.1

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Review by denisok — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1588-3452580
client docker - perconalab/pmm-client-fb:PR-1588-3452580
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1588-3452580.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1588-3452580&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1588-3452580.tar.gz

**Comment by rnovikovP** [comment]
This PR has some strange changes in clickhouse_exporter (99% thanks to the Submodules complexity), pls see https://github.com/Percona-Lab/pmm-submodules/pull/1589/files  this is what, I think, expected to be in this PR. Only  MongoDB exporter changes

**Review by rnovikovP — CHANGES_REQUESTED** [review]
Looks like here some unneeded changes to clickhouse exporter

**Comment by denisok** [comment]
> Looks like here some unneeded changes to clickhouse exporter

looks like github glitch. 

it compares our master to the fork master. here we don't change link to clickhouse or branch whatsoever....

**Comment by denisok** [comment]
> it compares our master to the fork master. here we don't change link to clickhouse or branch whatsoever....

there is no such `8b80aefd79020034c351243fdf067a7c4c24c61d` commit in our forked repo. It exists only in ` ClickHouse/clickhouse_exporter` .

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6279/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7319/

**Comment by denisok** [comment]
@percona-csalguero could you please check if you 

> > it compares our master to the fork master. here we don't change link to clickhouse or branch whatsoever....
> 
> there is no such `8b80aefd79020034c351243fdf067a7c4c24c61d` commit in our forked repo. It exists only in ` ClickHouse/clickhouse_exporter` .

dkondratenko@denlen:~/Workspace/github/pmm-submodules> git submodule status
-3c6a60b49e94a35a3a109a362b77381ebc364d49 sources/clickhouse_exporter/src/github.com/Percona-Lab/clickhouse_exporter

not a github issue, same in branch. @percona-csalguero could you please check why you branch has that commit ?

**Pull request closed without merging**
