### PR TITLE
PMM-3480 Pass params into url

### PR DESCRIPTION
**Pull request by darly-s**
- [ ] https://github.com/percona/qan-app/pull/309
- [ ] https://github.com/percona/grafana-dashboards/pull/307

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-3d081e6
client docker - perconalab/pmm-client-fb:PR-368-3d081e6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-3d081e6.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-4c4a049
client docker - perconalab/pmm-client-fb:PR-368-4c4a049
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-4c4a049.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-9473c2e
client docker - perconalab/pmm-client-fb:PR-368-9473c2e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-9473c2e.tar.gz

**Comment by puneet0191** [comment]
@darly-s I just checked this FB and I found an issue with Query Detail selection, Please take a look at this 
1) Click on Total for Query Details, nothing happens
2) Click on the first Query in the table, it shows data for Total. 
Issue with QAN Details selection

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-5208b5f
client docker - perconalab/pmm-client-fb:PR-368-5208b5f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-5208b5f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-c1eb671
client docker - perconalab/pmm-client-fb:PR-368-c1eb671
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-c1eb671.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-a62c8e0
client docker - perconalab/pmm-client-fb:PR-368-a62c8e0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-a62c8e0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-368-7a86de5
client docker - perconalab/pmm-client-fb:PR-368-7a86de5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-368-7a86de5.tar.gz

**Pull request closed without merging**
