### PR TITLE
PMM-6373 add sign in functionality

### PR DESCRIPTION
**Pull request by lunaticusgreen**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-27dffe5
client docker - perconalab/pmm-client-fb:PR-1039-27dffe5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-27dffe5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-ceac6cd
client docker - perconalab/pmm-client-fb:PR-1039-ceac6cd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-ceac6cd.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-02aa342
client docker - perconalab/pmm-client-fb:PR-1039-02aa342
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-02aa342.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-02aa342
client docker - perconalab/pmm-client-fb:PR-1039-02aa342
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-02aa342.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-02aa342
client docker - perconalab/pmm-client-fb:PR-1039-02aa342
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-02aa342.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-02aa342
client docker - perconalab/pmm-client-fb:PR-1039-02aa342
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-02aa342.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-69e72f6
client docker - perconalab/pmm-client-fb:PR-1039-69e72f6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-69e72f6.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-ea1b7ff
client docker - perconalab/pmm-client-fb:PR-1039-ea1b7ff
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-ea1b7ff.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1039-2bc8a52
client docker - perconalab/pmm-client-fb:PR-1039-2bc8a52
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1039-2bc8a52.tar.gz

**Comment by puneet0191** [comment]
I will close this FB, it doesn't bring in all changes due to conflicts.

**Comment by puneet0191** [comment]
The new one: https://github.com/Percona-Lab/pmm-submodules/pull/1047

**Pull request closed without merging**
