### PR TITLE
[FB] PMM-7313 PostgreSQL RDS

### PR DESCRIPTION
**Pull request by percona-csalguero**
Added PostreSQL RDS support.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-6f78dc2
client docker - perconalab/pmm-client-fb:PR-1563-6f78dc2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-6f78dc2.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-6f78dc2&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-6f78dc2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-2446c15
client docker - perconalab/pmm-client-fb:PR-1563-2446c15
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-2446c15.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-2446c15&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-2446c15.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-3a4f47e
client docker - perconalab/pmm-client-fb:PR-1563-3a4f47e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-3a4f47e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-3a4f47e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-3a4f47e.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6194/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5611/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7226/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-fb6df95
client docker - perconalab/pmm-client-fb:PR-1563-fb6df95
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-fb6df95.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-fb6df95&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-fb6df95.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6240/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5650/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7274/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-d72596c
client docker - perconalab/pmm-client-fb:PR-1563-d72596c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-d72596c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-d72596c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-d72596c.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6250/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5660/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7286/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-8acb714
client docker - perconalab/pmm-client-fb:PR-1563-8acb714
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-8acb714.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-8acb714&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-8acb714.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6253/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5663/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7289/

**Comment by puneet0191** [comment]
@percona-csalguero this FB is outdated, Please make sure you have updated with latest release/2.16

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-9e03d79
client docker - perconalab/pmm-client-fb:PR-1563-9e03d79
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-9e03d79.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-9e03d79&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-9e03d79.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-9e03d79
client docker - perconalab/pmm-client-fb:PR-1563-9e03d79
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-9e03d79.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-9e03d79&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-9e03d79.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1563-9e03d79
client docker - perconalab/pmm-client-fb:PR-1563-9e03d79
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-9e03d79.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1563-9e03d79&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1563-9e03d79.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6256/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5666/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7292/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6257/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5667/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7293/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6258/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5668/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7294/

**Pull request closed without merging**
