### PR TITLE
PMM-8461 Wait for settings before calling DBaaS API

### PR DESCRIPTION
**Pull request by tiagomotasantos**
https://github.com/percona-platform/grafana/pull/270

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2148-047a218
client docker - perconalab/pmm-client-fb:PR-2148-047a218
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2148-047a218.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2148-047a218&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2148-047a218.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/8535/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/10816/

**Comment by beatahandzelova** [comment]
> UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/10816/

https://github.com/percona/pmm-ui-tests/pull/136

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2148-3653ad6
client docker - perconalab/pmm-client-fb:PR-2148-3653ad6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2148-3653ad6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2148-3653ad6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2148-3653ad6.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/8542/

**Pull request closed without merging**
