### PR TITLE
PMM-3876 Sparklines points to interval

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-3876

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-241-a0456f9
client docker - perconalab/pmm-client-fb:PR-241-a0456f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-241-a0456f9.tar.gz

**Comment by rnovikovP** [comment]
image

**Comment by rnovikovP** [comment]
@darly-s when you have time, can you  combine  this FB  with https://github.com/Percona-Lab/pmm-submodules/pull/235 

Because   now, looks  overloaded and maybe  with onlya one sparkline  it  will be better. 

btw, pls return original color "orrange(?)" for sparkline

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-241-a0456f9
client docker - perconalab/pmm-client-fb:PR-241-a0456f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-241-a0456f9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-241-a0456f9
client docker - perconalab/pmm-client-fb:PR-241-a0456f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-241-a0456f9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-241-a0456f9
client docker - perconalab/pmm-client-fb:PR-241-a0456f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-241-a0456f9.tar.gz

**Comment by rnovikovP** [comment]
@darly-s  looks like we can close this because merged in 2.0 ?

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-241-a0456f9
client docker - perconalab/pmm-client-fb:PR-241-a0456f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-241-a0456f9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-241-a0456f9
client docker - perconalab/pmm-client-fb:PR-241-a0456f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-241-a0456f9.tar.gz

**Pull request closed without merging**
