### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1178-4372b37
client docker - perconalab/pmm-client-fb:PR-1178-4372b37
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1178-4372b37.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4599/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3981/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5182/

**Comment by AlekSi** [comment]
@BupycHuk Let's merge it

**Comment by puneet0191** [comment]
I will update version in the test, please go ahead and merge this too

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1178-4372b37
client docker - perconalab/pmm-client-fb:PR-1178-4372b37
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1178-4372b37.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4610/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3992/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5195/

**Pull request merged**
