### PR TITLE
PMM-7584 Update VictoriaMetrics 1.53.1 to 1.54.1

### PR DESCRIPTION
**Pull request by adivinho**
- [ ] https://github.com/Percona-Lab/pmm-submodules/pull/1560

### CODE REVIEW

**Review by BupycHuk — DISMISSED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1561-6e87857
client docker - perconalab/pmm-client-fb:PR-1561-6e87857
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1561-6e87857.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1561-6e87857&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1561-6e87857.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1561-6e87857
client docker - perconalab/pmm-client-fb:PR-1561-6e87857
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1561-6e87857.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1561-6e87857&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1561-6e87857.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6172/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5589/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7202/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1561-194f382
client docker - perconalab/pmm-client-fb:PR-1561-194f382
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1561-194f382.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1561-194f382&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1561-194f382.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6417/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5827/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7478/

**Pull request closed without merging**
