### PR TITLE
PMM-5329 Update Prometheus to version 2.15.2

### PR DESCRIPTION
**Pull request by adivinho**
- [ ] https://github.com/percona/pmm-server-packaging/pull/108

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-641-8625a03
client docker - perconalab/pmm-client-fb:PR-641-8625a03
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-641-8625a03.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-641-c3c9b0f
client docker - perconalab/pmm-client-fb:PR-641-c3c9b0f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-641-c3c9b0f.tar.gz

**Comment by adivinho** [comment]
> Let's stop adding things to this `if`. Please work with @hors to do that properly.

Let's make it as a separate task. Rewriting structure of build scripts is hardly related to the current task.
@hors ?

**Comment by AlekSi** [comment]
> Rewriting structure of build scripts is hardly related to the current task.

That's what you did there. Before this PR all Prometheus build commands were there: https://github.com/percona/pmm-server-packaging/blob/2607181a3019d57e3796c4f0a7cc2936d76ca796/rhel/SPECS/prometheus.spec#L40-L71 Now they are split between two places. That's not okay.

**Comment by hors** [comment]
> Let's stop adding things to this `if`. Please work with @hors to do that properly.

@AlekSi  @adivinho  As I know we will update go in our build docker to ver 13 to next release and we can enable repo for yarn too, so changes in pmm-submodules are not needed at all.

**Pull request closed without merging**
