### PR TITLE
PMM-2519 Query Analytics Visual Explain	

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-2541

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-43-acf14c1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-43-acf14c1.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-43-8dc09e8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-43-8dc09e8.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-43-36469f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-43-36469f9.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/qan-app/pull/106  marged

**Pull request closed without merging**
