### PR TITLE
PMM-9599-config-custom-labels

### PR DESCRIPTION
**Pull request by ghost**
https://jira.percona.com/browse/PMM-9599

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2740-4dc41a5
client docker - perconalab/pmm-client-fb:PR-2740-4dc41a5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2740-4dc41a5.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2740-4dc41a5&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2740-4dc41a5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2740-4dc41a5
client docker - perconalab/pmm-client-fb:PR-2740-4dc41a5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2740-4dc41a5.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2740-4dc41a5&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2740-4dc41a5.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/10641/

**Comment by ErikaDoniecova** [comment]
The pipeline went through without new failures https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/959/pipeline

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2740-0975486
client docker - perconalab/pmm-client-fb:PR-2740-0975486
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2740-0975486.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2740-0975486&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2740-0975486.tar.gz

**Comment by nazarovvi** [comment]
Bats test is fixed https://pmm.cd.percona.com/job/pmm2-testsuite/10668/

**Pull request closed without merging**
