### PR TITLE
PMM-10067 Use Toolkit 3.4.0

### PR DESCRIPTION
**Pull request by percona-csalguero**
https://jira.percona.com/browse/PMM-10067

Feature Build https://github.com/Percona-Lab/pmm-submodules/pull/2532 was tested OK

### CODE REVIEW

**Review by denisok — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2544-199f2b0
client docker - perconalab/pmm-client-fb:PR-2544-199f2b0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2544-199f2b0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2544-199f2b0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2544-199f2b0.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10183/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/16442/

**Review by BupycHuk — APPROVED** [review]

**Comment by denisok** [comment]
probably here as well? https://github.com/Percona-Lab/pmm-submodules/blob/PMM-2.0/ci-default.yml#L59 ?

**Pull request merged**
