### PR TITLE
PMM-3677 remove orchestrator from pmm2

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-204-65262f0
client docker - perconalab/pmm-client-fb:PR-204-65262f0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-204-65262f0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-204-907b077
client docker - perconalab/pmm-client-fb:PR-204-907b077
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-204-907b077.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server-packaging/pull/29
https://github.com/percona/pmm-server/pull/125
https://github.com/percona/pmm-update/pull/21/

**Comment by peterschwaller** [comment]
Dummy comment to trigger sync to Jira.  Please ignore.

**Pull request merged**
