### PR TITLE
PMM-2912 PMM 2.0 (sandbox)

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-b995198
client docker - perconalab/pmm-client-fb:PR-129-b995198
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-b995198.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-b995198
client docker - perconalab/pmm-client-fb:PR-129-b995198
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-b995198.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-7e522a3
client docker - perconalab/pmm-client-fb:PR-129-7e522a3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-7e522a3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-ec2eb8b
client docker - perconalab/pmm-client-fb:PR-129-ec2eb8b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-ec2eb8b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-b835b5b
client docker - perconalab/pmm-client-fb:PR-129-b835b5b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-b835b5b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-22c5926
client docker - perconalab/pmm-client-fb:PR-129-22c5926
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-22c5926.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-0037663
client docker - perconalab/pmm-client-fb:PR-129-0037663
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-0037663.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-0037663
client docker - perconalab/pmm-client-fb:PR-129-0037663
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-0037663.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-0037663
client docker - perconalab/pmm-client-fb:PR-129-0037663
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-0037663.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-e1f442c
client docker - perconalab/pmm-client-fb:PR-129-e1f442c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-e1f442c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-3106c51
client docker - perconalab/pmm-client-fb:PR-129-3106c51
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-3106c51.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-1b0f68c
client docker - perconalab/pmm-client-fb:PR-129-1b0f68c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-1b0f68c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-ede3ed2
client docker - perconalab/pmm-client-fb:PR-129-ede3ed2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-ede3ed2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-ede3ed2
client docker - perconalab/pmm-client-fb:PR-129-ede3ed2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-ede3ed2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-8eba546
client docker - perconalab/pmm-client-fb:PR-129-8eba546
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-8eba546.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-82f6778
client docker - perconalab/pmm-client-fb:PR-129-82f6778
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-82f6778.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-82f6778
client docker - perconalab/pmm-client-fb:PR-129-82f6778
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-82f6778.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-c310fcc
client docker - perconalab/pmm-client-fb:PR-129-c310fcc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-c310fcc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-d24a1c9
client docker - perconalab/pmm-client-fb:PR-129-d24a1c9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-d24a1c9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-3d0ef96
client docker - perconalab/pmm-client-fb:PR-129-3d0ef96
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-3d0ef96.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-47108c4
client docker - perconalab/pmm-client-fb:PR-129-47108c4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-47108c4.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-370316c
client docker - perconalab/pmm-client-fb:PR-129-370316c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-370316c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-20b891a
client docker - perconalab/pmm-client-fb:PR-129-20b891a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-20b891a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-592d17b
client docker - perconalab/pmm-client-fb:PR-129-592d17b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-592d17b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-592d17b
client docker - perconalab/pmm-client-fb:PR-129-592d17b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-592d17b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-592d17b
client docker - perconalab/pmm-client-fb:PR-129-592d17b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-592d17b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-592d17b
client docker - perconalab/pmm-client-fb:PR-129-592d17b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-592d17b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-07e3787
client docker - perconalab/pmm-client-fb:PR-129-07e3787
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-07e3787.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-07e3787
client docker - perconalab/pmm-client-fb:PR-129-07e3787
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-07e3787.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-653b7c1
client docker - perconalab/pmm-client-fb:PR-129-653b7c1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-653b7c1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-95f44e3
client docker - perconalab/pmm-client-fb:PR-129-95f44e3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-95f44e3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-95f44e3
client docker - perconalab/pmm-client-fb:PR-129-95f44e3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-95f44e3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-b3b06ff
client docker - perconalab/pmm-client-fb:PR-129-b3b06ff
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-b3b06ff.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-68594cb
client docker - perconalab/pmm-client-fb:PR-129-68594cb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-68594cb.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-68594cb
client docker - perconalab/pmm-client-fb:PR-129-68594cb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-68594cb.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-a29dc89
client docker - perconalab/pmm-client-fb:PR-129-a29dc89
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-a29dc89.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-98aae31
client docker - perconalab/pmm-client-fb:PR-129-98aae31
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-98aae31.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-a29dc89
client docker - perconalab/pmm-client-fb:PR-129-a29dc89
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-a29dc89.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-a29dc89
client docker - perconalab/pmm-client-fb:PR-129-a29dc89
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-a29dc89.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-197b8c8
client docker - perconalab/pmm-client-fb:PR-129-197b8c8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-197b8c8.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-197b8c8
client docker - perconalab/pmm-client-fb:PR-129-197b8c8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-197b8c8.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-d368255
client docker - perconalab/pmm-client-fb:PR-129-d368255
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-d368255.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-d368255
client docker - perconalab/pmm-client-fb:PR-129-d368255
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-d368255.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-f83d0a9
client docker - perconalab/pmm-client-fb:PR-129-f83d0a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-f83d0a9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-f83d0a9
client docker - perconalab/pmm-client-fb:PR-129-f83d0a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-f83d0a9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-129-f83d0a9
client docker - perconalab/pmm-client-fb:PR-129-f83d0a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-129-f83d0a9.tar.gz

**Comment by rnovikovP** [comment]
outdated see https://github.com/Percona-Lab/pmm-submodules/pull/169

**Pull request closed without merging**
