### PR TITLE
PMM-5819 [FB] Setting for STT

### PR DESCRIPTION
**Pull request by percona-csalguero**
**Jira**: https://jira.percona.com/browse/PMM-5819
UI: https://jira.percona.com/browse/PMM-5820

**Related PRs**

- [x] https://github.com/percona/pmm/pull/515
- [x] https://github.com/percona/pmm-managed/pull/375
- [ ] https://github.com/percona/grafana-dashboards/pull/664
- [x] https://github.com/Percona-Lab/pmm-api-tests/pull/91

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-3a77053
client docker - perconalab/pmm-client-fb:PR-809-3a77053
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-3a77053.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-4ef444c
client docker - perconalab/pmm-client-fb:PR-809-4ef444c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-4ef444c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-ab2963c
client docker - perconalab/pmm-client-fb:PR-809-ab2963c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-ab2963c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-1a91f05
client docker - perconalab/pmm-client-fb:PR-809-1a91f05
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-1a91f05.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-9adeaff
client docker - perconalab/pmm-client-fb:PR-809-9adeaff
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-9adeaff.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-5027a48
client docker - perconalab/pmm-client-fb:PR-809-5027a48
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-5027a48.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-94541f0
client docker - perconalab/pmm-client-fb:PR-809-94541f0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-94541f0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-f9bd84a
client docker - perconalab/pmm-client-fb:PR-809-f9bd84a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-f9bd84a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-151d4cf
client docker - perconalab/pmm-client-fb:PR-809-151d4cf
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-151d4cf.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-b2c30a1
client docker - perconalab/pmm-client-fb:PR-809-b2c30a1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-b2c30a1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-809-fe520ce
client docker - perconalab/pmm-client-fb:PR-809-fe520ce
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-809-fe520ce.tar.gz

**Comment by AlekSi** [comment]
See https://github.com/Percona-Lab/pmm-submodules/pull/818

**Pull request closed without merging**
