### PR TITLE
PMM-7925: Add SystemD service with podman to run PMM

### PR DESCRIPTION
**Pull request by denisok**
https://jira.percona.com/browse/PMM-7925

- https://github.com/percona/pmm-server/pull/355
- https://github.com/percona/pmm-doc/pull/759

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2440-469d66f
client docker - perconalab/pmm-client-fb:PR-2440-469d66f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2440-469d66f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2440-469d66f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2440-469d66f.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9656/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/13851/

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm-server/pull/355

**Comment by puneet0191** [comment]
@denisok could you update pmm-server branch?

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2440-bf336f9
client docker - perconalab/pmm-client-fb:PR-2440-bf336f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2440-bf336f9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2440-bf336f9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2440-bf336f9.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10170/

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/9693/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/16367/

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm-server/pull/355

**Pull request closed without merging**
