### PR TITLE
PMM-7653 Update mongodb_exporter to release 0.20.3

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Review by denisok — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1582-7faa7c4
client docker - perconalab/pmm-client-fb:PR-1582-7faa7c4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1582-7faa7c4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1582-7faa7c4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1582-7faa7c4.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7302/

**Review by rnovikovP — APPROVED** [review]

**Comment by percona-csalguero** [comment]
Closing this in favor of https://github.com/Percona-Lab/pmm-submodules/pull/1587 which is based on `release/2.16`

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1582-7faa7c4
client docker - perconalab/pmm-client-fb:PR-1582-7faa7c4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1582-7faa7c4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1582-7faa7c4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1582-7faa7c4.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7314/

**Pull request closed without merging**
