### PR TITLE
PMM-2704: postgresql:metrics +  PMM-2486: Option to disable SSL for exporters

### PR DESCRIPTION
**Pull request by arvenil**
* PMM-2704: postgresql:metrics
  Check usage instructions that worked for me: https://github.com/percona/pmm-client/pull/157
* PMM-2486: Option to disable SSL for exporters

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-24cf44e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-24cf44e.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-808d839
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-808d839.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-5edfd04
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-5edfd04.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-cdaeaa1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-cdaeaa1.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-5806e83
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-5806e83.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-6a29cd9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-6a29cd9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-54cec37
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-54cec37.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-fb0e2ee
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-fb0e2ee.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-cb6b9e4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-cb6b9e4.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-ded58c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-ded58c0.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-ded58c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-ded58c0.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-d08cbe9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-d08cbe9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-b9736c8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-b9736c8.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-e065f7e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-e065f7e.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-7313dd0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-7313dd0.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/postgres_exporter/pull/1  merged 
https://github.com/percona/grafana-dashboards/pull/235 merged  (but expect some additional changes )
https://github.com/percona/pmm-client/pull/157 merged 
https://github.com/percona/pmm-server/pull/75 merged

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-68-7313dd0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-68-7313dd0.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/73 merged

**Pull request closed without merging**
