### PR TITLE
PMM-7 update GH status action repo

### PR DESCRIPTION
**Pull request by yurkovychv**
https://jira.percona.com/browse/PMM-0

- [ ] Links to relevant pull requests

### CODE REVIEW

**Comment by JNKPercona** [comment]
PMM3 Submodules skipped

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3457-8c759ef
client docker - perconalab/pmm-client-fb:PR-3457-8c759ef
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3457-8c759ef.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3457-8c759ef&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3457-8c759ef.tar.gz

**Comment by JNKPercona** [comment]
PMM3 Submodules skipped

**Review by vyarosh — APPROVED** [review]
Looks good to me!

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3457-4e20864
client docker - perconalab/pmm-client-fb:PR-3457-4e20864
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3457-4e20864.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3457-4e20864&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3457-4e20864.tar.gz

**Pull request merged**
