### PR TITLE
PMM-6208 SAAS-125 Silence STT checks

### PR DESCRIPTION
**Pull request by nicolalamacchia**
- [ ] https://github.com/percona/grafana-dashboards/pull/833
- [x] https://github.com/percona/pmm-managed/pull/405
- [x] https://github.com/Percona-Lab/pmm-api-tests/pull/114

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-6f84559
client docker - perconalab/pmm-client-fb:PR-948-6f84559
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-6f84559.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-7e1e76b
client docker - perconalab/pmm-client-fb:PR-948-7e1e76b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-7e1e76b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-1165eae
client docker - perconalab/pmm-client-fb:PR-948-1165eae
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-1165eae.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-397c8f4
client docker - perconalab/pmm-client-fb:PR-948-397c8f4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-397c8f4.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-0b938d5
client docker - perconalab/pmm-client-fb:PR-948-0b938d5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-0b938d5.tar.gz

**Comment by AlekSi** [comment]
Backend PRs were merged

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-e6e689c
client docker - perconalab/pmm-client-fb:PR-948-e6e689c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-e6e689c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-d7fa723
client docker - perconalab/pmm-client-fb:PR-948-d7fa723
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-d7fa723.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-30a1230
client docker - perconalab/pmm-client-fb:PR-948-30a1230
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-30a1230.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-948-e54b0b2
client docker - perconalab/pmm-client-fb:PR-948-e54b0b2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-948-e54b0b2.tar.gz

**Pull request closed without merging**
