### PR TITLE
Fixed branches for 1.X version

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-133-104c47a
client docker - perconalab/pmm-client-fb:PR-133-104c47a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-133-104c47a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-133-401ba3d
client docker - perconalab/pmm-client-fb:PR-133-401ba3d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-133-401ba3d.tar.gz

**Comment by rnovikovP** [comment]
Moving 1.X  exporter versions to separate branch to be used in builds to let us work on Exporters in master and add something we not ready to include in  PMM right now.

This approach needs to be revisited before 2.0 release

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-133-4df7ca7
client docker - perconalab/pmm-client-fb:PR-133-4df7ca7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-133-4df7ca7.tar.gz

**Pull request merged**
