### PR TITLE
PMM-7336 Feature build

### PR DESCRIPTION
**Pull request by artemgavrilov**
[PMM-7336](https://jira.percona.com/browse/PMM-7336)

- [ ] https://github.com/percona/pmm-managed/pull/672

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-4b314ad
client docker - perconalab/pmm-client-fb:PR-1544-4b314ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-4b314ad.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-4b314ad&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-4b314ad.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6121/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5538/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7130/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-a60bf72
client docker - perconalab/pmm-client-fb:PR-1544-a60bf72
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-a60bf72.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-a60bf72&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-a60bf72.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-e11dfb2
client docker - perconalab/pmm-client-fb:PR-1544-e11dfb2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-e11dfb2.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-e11dfb2&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-e11dfb2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-7d795d5
client docker - perconalab/pmm-client-fb:PR-1544-7d795d5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-7d795d5.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-7d795d5&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-7d795d5.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6130/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5547/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7144/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-808d217
client docker - perconalab/pmm-client-fb:PR-1544-808d217
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-808d217.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-808d217&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-808d217.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6132/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5549/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7146/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-45a888f
client docker - perconalab/pmm-client-fb:PR-1544-45a888f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-45a888f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-45a888f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-45a888f.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6137/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5554/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7152/

**Comment by yurkovychv** [comment]
please ignore those 4 [failing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7152/tests) tests , fixing them

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1544-736757b
client docker - perconalab/pmm-client-fb:PR-1544-736757b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-736757b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1544-736757b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1544-736757b.tar.gz

**Pull request closed without merging**
