### PR TITLE
PMM-8575 Migrate toolkit to modules

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Review by nikita-b — DISMISSED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2008-33fe358
client docker - perconalab/pmm-client-fb:PR-2008-33fe358
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2008-33fe358.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2008-33fe358&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2008-33fe358.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7901/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2008-6bcc030
client docker - perconalab/pmm-client-fb:PR-2008-6bcc030
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2008-6bcc030.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2008-6bcc030&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2008-6bcc030.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/8013/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/10037/

**Comment by percona-csalguero** [comment]
Superseded by https://github.com/Percona-Lab/pmm-submodules/pull/2069

**Pull request closed without merging**
