### PR TITLE
PMM-7618 PMM Submenu migration

### PR DESCRIPTION
**Pull request by lunaticusgreen**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1595-e38cbe2
client docker - perconalab/pmm-client-fb:PR-1595-e38cbe2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-e38cbe2.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1595-e38cbe2&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-e38cbe2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1595-bd5b812
client docker - perconalab/pmm-client-fb:PR-1595-bd5b812
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-bd5b812.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1595-bd5b812&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-bd5b812.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6293/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5703/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7335/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1595-0eeb3cc
client docker - perconalab/pmm-client-fb:PR-1595-0eeb3cc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-0eeb3cc.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1595-0eeb3cc&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-0eeb3cc.tar.gz

**Comment by puneet0191** [comment]
Probably need to build a fresh FB, because this seems really outdated and causing failures on tests @lunaticusgreen

**Comment by lunaticusgreen** [comment]
> Probably need to build a fresh FB, because this seems really outdated and causing failures on tests @lunaticusgreen

But it was created just yesterday and I synced all branches 🙀  @puneet0191

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1595-389fa65
client docker - perconalab/pmm-client-fb:PR-1595-389fa65
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-389fa65.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1595-389fa65&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1595-389fa65.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6313/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5723/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7358/

**Pull request closed without merging**
