### PR TITLE
PMM-2154 New Build Dashboard for MySQL Command Counters

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-24a2976
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-24a2976.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-82869e2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-82869e2.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-3a22958
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-3a22958.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-3a22958
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-3a22958.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-89677c9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-89677c9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-3da6f59
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-3da6f59.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-54-aa066b4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-54-aa066b4.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/184   merged

**Pull request closed without merging**
