### PR TITLE
PMM-10103 add rhel 9

### PR DESCRIPTION
**Pull request by nikita-b**
https://jira.percona.com/browse/PMM-0

- [ ] Links to other linked pull requests.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2573-c6e774b
client docker - perconalab/pmm-client-fb:PR-2573-c6e774b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2573-c6e774b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2573-c6e774b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2573-c6e774b.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10321/

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/9845/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/17236/

**Comment by JNKPercona** [comment]
Dockerway Upgrade tests have failed, Please check: Upgrade: https://pmm.cd.percona.com/job/pmm2-upgrade-tests/15673/

**Review by ademidoff — APPROVED** [review]

**Review by denisok — APPROVED** [review]

**Pull request closed without merging**
