### PR TITLE
move jenkinsfile to jenkins-pipelines repo

### PR DESCRIPTION
**Pull request by nikita-b**
https://github.com/Percona-Lab/jenkins-pipelines/pull/1188

### CODE REVIEW

**Review by ademidoff — APPROVED** [review]

**Comment by ademidoff** [comment]
@nikita-b Question: do wee need to rebase all open PRs in this repo after we merge this one?

**Comment by nikita-b** [comment]
@atymchuk I think we don't need it. We changed settings in Jenkins and it'll take Jenkinsfile from another repo.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1996-4f14121
client docker - perconalab/pmm-client-fb:PR-1996-4f14121
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1996-4f14121.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1996-4f14121&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1996-4f14121.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7849/

**Pull request merged**
