### PR TITLE
PMM-2323-Enable-NUMA-Collector-by-default

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-31-c1f9fc5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-31-c1f9fc5.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-31-c1f9fc5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-31-c1f9fc5.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-31-986c246
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-31-986c246.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-31-986c246
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-31-986c246.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-31-986c246
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-31-986c246.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-client/pull/121
https://github.com/percona/grafana-dashboards/pull/185
merged

**Pull request closed without merging**
