### PR TITLE
PMM-7405 Check conn for external exporters.

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-7405

Ref: 
 - https://github.com/percona/pmm-admin/pull/135
 - https://github.com/percona/pmm-managed/pull/659
 - https://github.com/percona/pmm/pull/679
 - https://github.com/percona/pmm-agent/pull/231
 - https://github.com/Percona-Lab/pmm-api-tests/pull/194
Test examples:

```
[root@255399f5b249 /]# pmm-admin add external-serverless --host=redis_exporter --listen-port=9121 --scheme='http' --metrics-path='metrics' --external-name=external-name1
External Service added.
Service ID  : /service_id/32d75031-863b-4583-ab09-ba310c4eb7d1
Service name: external-name1
Group       : external

[root@255399f5b249 /]# pmm-admin add external-serverless --host=redis_exporter --listen-port=9121 --scheme='httpx' --metrics-path='metrics' --external-name=external-name2
Connection check failed: Get "httpx://redis_exporter:9121/metrics": unsupported protocol scheme "httpx".
[root@255399f5b249 /]# pmm-admin add external-serverless --host=redis_exporter --listen-port=9122 --scheme='http' --metrics-path='metrics' --external-name=external-name2
Connection check failed: Get "http://redis_exporter:9122/metrics": dial tcp 172.29.0.2:9122: connect: connection refused.
[root@255399f5b249 /]# pmm-admin add external-serverless --host=redis_exporter_unknown_host --listen-port=9121 --scheme='http' --metrics-path='metrics' --external-name=external-name2
Connection check failed: Get "http://redis_exporter_unknown_host:9121/metrics": dial tcp: lookup redis_exporter_unknown_host on 127.0.0.11:53: no such host.
[root@255399f5b249 /]# ping redis_exporter
PING redis_exporter (172.29.0.2) 56(84) bytes of data.
64 bytes from redis_exporter.qan-api2_default (172.29.0.2): icmp_seq=1 ttl=64 time=0.552 ms
^C
--- redis_exporter ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.552/0.552/0.552/0.000 ms
[root@255399f5b249 /]# pmm-admin add external-serverless --host=172.29.0.2 --listen-port=9121 --scheme='http' --metrics-path='metrics' --external-name=external-name2
External Service added.
Service ID  : /service_id/afcec6d8-e677-4bbf-86e6-3b5722072e31
Service name: external-name2
Group       : external


```

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1518-f3f0560
client docker - perconalab/pmm-client-fb:PR-1518-f3f0560
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-f3f0560.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1518-f3f0560&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-f3f0560.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6003/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5420/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6976/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1518-5f5c077
client docker - perconalab/pmm-client-fb:PR-1518-5f5c077
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-5f5c077.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1518-5f5c077&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-5f5c077.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1518-1436373
client docker - perconalab/pmm-client-fb:PR-1518-1436373
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-1436373.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1518-1436373&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-1436373.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6025/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5442/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7007/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6026/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5443/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7008/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1518-957f497
client docker - perconalab/pmm-client-fb:PR-1518-957f497
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-957f497.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1518-957f497&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1518-957f497.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6038/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5455/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7024/

**Comment by yurkovychv** [comment]
Please ignore failed UI tests. Fixing those right now

**Pull request closed without merging**
