### PR TITLE
SAAS-175 Auth API

### PR DESCRIPTION
**Pull request by artemgavrilov**
- https://jira.percona.com/browse/SAAS-175

- [x] https://github.com/Percona-Lab/jenkins-pipelines/pull/499
- [x] https://github.com/percona/pmm/pull/553
- [x] https://github.com/percona/pmm-managed/pull/420
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/116

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-11cf1d9
client docker - perconalab/pmm-client-fb:PR-967-11cf1d9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-11cf1d9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-40866c5
client docker - perconalab/pmm-client-fb:PR-967-40866c5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-40866c5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-c95347c
client docker - perconalab/pmm-client-fb:PR-967-c95347c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-c95347c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-c95347c
client docker - perconalab/pmm-client-fb:PR-967-c95347c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-c95347c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-7e3f50c
client docker - perconalab/pmm-client-fb:PR-967-7e3f50c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-7e3f50c.tar.gz

**Comment by artemgavrilov** [comment]
Blocked by: https://github.com/Percona-Lab/jenkins-pipelines/pull/499

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-90abd04
client docker - perconalab/pmm-client-fb:PR-967-90abd04
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-90abd04.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-ddcbffa
client docker - perconalab/pmm-client-fb:PR-967-ddcbffa
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-ddcbffa.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-99b4609
client docker - perconalab/pmm-client-fb:PR-967-99b4609
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-99b4609.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-74570b5
client docker - perconalab/pmm-client-fb:PR-967-74570b5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-74570b5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-5778943
client docker - perconalab/pmm-client-fb:PR-967-5778943
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-5778943.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-2daa92f
client docker - perconalab/pmm-client-fb:PR-967-2daa92f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-2daa92f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-bd6d7f9
client docker - perconalab/pmm-client-fb:PR-967-bd6d7f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-bd6d7f9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-0090ffc
client docker - perconalab/pmm-client-fb:PR-967-0090ffc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-0090ffc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-ceaa715
client docker - perconalab/pmm-client-fb:PR-967-ceaa715
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-ceaa715.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-b5b08ab
client docker - perconalab/pmm-client-fb:PR-967-b5b08ab
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-b5b08ab.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-4afe65c
client docker - perconalab/pmm-client-fb:PR-967-4afe65c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-4afe65c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-967-b16db44
client docker - perconalab/pmm-client-fb:PR-967-b16db44
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-967-b16db44.tar.gz

**Pull request closed without merging**
