### PR TITLE
PMM-5231 Wrong keys in rds_exporter config.

### PR DESCRIPTION
**Pull request by puneet0191**
- [ ] https://github.com/percona/pmm-managed/pull/323

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-608-0de745f
client docker - perconalab/pmm-client-fb:PR-608-0de745f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-608-0de745f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-608-fdbf84c
client docker - perconalab/pmm-client-fb:PR-608-fdbf84c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-608-fdbf84c.tar.gz

**Comment by rnovikovP** [comment]
note: we  don't need to merge this  PR, just use this for  FB and  close when  everything tested

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-608-a14f060
client docker - perconalab/pmm-client-fb:PR-608-a14f060
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-608-a14f060.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-608-1957a39
client docker - perconalab/pmm-client-fb:PR-608-1957a39
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-608-1957a39.tar.gz

**Pull request closed without merging**
