### PR TITLE
Release mongo exporter 0.30.0

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2170-2dfefbb
client docker - perconalab/pmm-client-fb:PR-2170-2dfefbb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2170-2dfefbb.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2170-2dfefbb&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2170-2dfefbb.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/8660/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2170-dd49192
client docker - perconalab/pmm-client-fb:PR-2170-dd49192
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2170-dd49192.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2170-dd49192&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2170-dd49192.tar.gz

**Review by denisok — CHANGES_REQUESTED** [review]
please remove sumbodules update from this PR. ` sources/mongodb_exporter/src/github.com/percona/mongodb_exporter ` shouldn't be here.

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
