### PR TITLE
PMM-12557 Automate PMM3 builds

### PR DESCRIPTION
**Pull request by surbhat1595**
https://jira.percona.com/browse/PMM-12557

- [ ] Links to relevant pull requests

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-aca7607
client docker - perconalab/pmm-client-fb:PR-3426-aca7607
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-aca7607.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-aca7607&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-aca7607.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-aca7607
client docker - perconalab/pmm-client-fb:PR-3426-aca7607
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-aca7607.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-aca7607&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-aca7607.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm3-api-tests/1/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-0a96d4d
client docker - perconalab/pmm-client-fb:PR-3426-0a96d4d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-0a96d4d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-0a96d4d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-0a96d4d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm3-api-tests/3/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-74a2409
client docker - perconalab/pmm-client-fb:PR-3426-74a2409
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-74a2409.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-74a2409&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm3-client/pmm3-client-PR-3426-74a2409.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-0080110
client docker - perconalab/pmm-client-fb:PR-3426-0080110
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-0080110.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-0080110&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-0080110.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-0080110
client docker - perconalab/pmm-client-fb:PR-3426-0080110
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-0080110.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-0080110&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-0080110.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-e8b24d6
client docker - perconalab/pmm-client-fb:PR-3426-e8b24d6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-e8b24d6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-e8b24d6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-e8b24d6.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm3-api-tests/6/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-d5e75ea
client docker - perconalab/pmm-client-fb:PR-3426-d5e75ea
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-d5e75ea.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-d5e75ea&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-d5e75ea.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-a6aee8d
client docker - perconalab/pmm-client-fb:PR-3426-a6aee8d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-a6aee8d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-a6aee8d
client docker - perconalab/pmm-client-fb:PR-3426-a6aee8d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-a6aee8d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm-api-tests/1/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-a6aee8d
client docker - perconalab/pmm-client-fb:PR-3426-a6aee8d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-a6aee8d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm-api-tests/2/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-a6aee8d
client docker - perconalab/pmm-client-fb:PR-3426-a6aee8d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-a6aee8d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm-api-tests/3/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-a6aee8d
client docker - perconalab/pmm-client-fb:PR-3426-a6aee8d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-a6aee8d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-a6aee8d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm-api-tests/4/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-81dab72
client docker - perconalab/pmm-client-fb:PR-3426-81dab72
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-81dab72.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start-pmm3/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-81dab72&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3426-81dab72.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm-api-tests/5/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3426-ebc065b
client docker - perconalab/pmm-client-fb:PR-3426-ebc065b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3426-ebc065b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3426-ebc065b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3426-ebc065b.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14537/

**Review by BupycHuk — APPROVED** [review]

**Review by artemgavrilov — APPROVED** [review]

**Review by talhabinrizwan — APPROVED** [review]

**Pull request merged**
