### PR TITLE
PMM-5631 Broken Copyrights placement on some PMMDemo dashboards

### PR DESCRIPTION
**Pull request by adivinho**
- [x] https://github.com/percona/pmm-server/pull/215
- [x] https://github.com/percona/grafana-dashboards/pull/764

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-891-780bbf0
client docker - perconalab/pmm-client-fb:PR-891-780bbf0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-891-780bbf0.tar.gz

**Comment by AlekSi** [comment]
@adivinho It wasn't updated with recent changes, and tests fail

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-891-73fd9f2
client docker - perconalab/pmm-client-fb:PR-891-73fd9f2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-891-73fd9f2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-891-73fd9f2
client docker - perconalab/pmm-client-fb:PR-891-73fd9f2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-891-73fd9f2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-891-dd2217b
client docker - perconalab/pmm-client-fb:PR-891-dd2217b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-891-dd2217b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-891-0e32b6e
client docker - perconalab/pmm-client-fb:PR-891-0e32b6e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-891-0e32b6e.tar.gz

**Comment by adivinho** [comment]
@AlekSi,  Done.
There is still a failure in UI tests that has no relation to my changes. 
@yurkovychv has been informed.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-891-f1cc087
client docker - perconalab/pmm-client-fb:PR-891-f1cc087
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-891-f1cc087.tar.gz

**Comment by yurkovychv** [comment]
@AlekSi the the failing UI test is not related to this FB. Looking at the solution right now

**Pull request closed without merging**
