### PR TITLE
PMM-10403 Trigger FB

### PR DESCRIPTION
**Pull request by floatinginbits**
[PMM-10403](https://jira.percona.com/browse/PMM-10403) : Add API for user data in PMM

- [ ] https://github.com/percona/pmm/pull/1168

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2735-2a86387
client docker - perconalab/pmm-client-fb:PR-2735-2a86387
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2735-2a86387.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2735-2a86387&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2735-2a86387.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/10601/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2735-266c2c0
client docker - perconalab/pmm-client-fb:PR-2735-266c2c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2735-266c2c0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2735-266c2c0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2735-266c2c0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2735-4aefd37
client docker - perconalab/pmm-client-fb:PR-2735-4aefd37
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2735-4aefd37.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2735-4aefd37&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2735-4aefd37.tar.gz

**Comment by ErikaDoniecova** [comment]
All tests passed without new failures https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/967/pipeline/24/

**Pull request closed without merging**
