### PR TITLE
PMM-8279: Implement ECR for RPMBuild docker image

### PR DESCRIPTION
**Pull request by Sudokamikaze**
Builds: https://pmm.cd.percona.com/job/pmm-submodules/job/PR-1873/7/

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1873-e252cc2
client docker - perconalab/pmm-client-fb:PR-1873-e252cc2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1873-e252cc2.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1873-e252cc2&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1873-e252cc2.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8956/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1873-06f415e
client docker - perconalab/pmm-client-fb:PR-1873-06f415e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1873-06f415e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1873-06f415e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1873-06f415e.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/6704/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8961/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1873-bf242ed
client docker - perconalab/pmm-client-fb:PR-1873-bf242ed
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1873-bf242ed.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1873-bf242ed&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1873-bf242ed.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8969/

**Review by EvgeniyPatlan — APPROVED** [review]

**Review by ademidoff — APPROVED** [review]

**Pull request merged**
