### PR TITLE
Update Go.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-375-8530894
client docker - perconalab/pmm-client-fb:PR-375-8530894
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-375-8530894.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-375-c862d2c
client docker - perconalab/pmm-client-fb:PR-375-c862d2c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-375-c862d2c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-375-c862d2c
client docker - perconalab/pmm-client-fb:PR-375-c862d2c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-375-c862d2c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-375-1cce9f7
client docker - perconalab/pmm-client-fb:PR-375-1cce9f7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-375-1cce9f7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-375-4428dbd
client docker - perconalab/pmm-client-fb:PR-375-4428dbd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-375-4428dbd.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-375-7e7d704
client docker - perconalab/pmm-client-fb:PR-375-7e7d704
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-375-7e7d704.tar.gz

**Comment by AlekSi** [comment]
Re-doing it in #402.

**Pull request closed without merging**
