### PR TITLE
PMM-2520 Explain Missing Charts from MySQL Dashboards

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-48-a41e542
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-48-a41e542.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-48-0e6a7d6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-48-0e6a7d6.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-48-98cd38c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-48-98cd38c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-48-98cd38c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-48-98cd38c.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/190 merged

**Pull request closed without merging**
