### PR TITLE
PMM-5029 Upload snapshots to Percona not working

### PR DESCRIPTION
**Pull request by adivinho**
- [ ] https://github.com/percona/pmm-update/pull/75

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-543-60b23bc
client docker - perconalab/pmm-client-fb:PR-543-60b23bc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-543-60b23bc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-543-e736471
client docker - perconalab/pmm-client-fb:PR-543-e736471
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-543-e736471.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-543-e736471
client docker - perconalab/pmm-client-fb:PR-543-e736471
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-543-e736471.tar.gz

**Comment by rnovikovP** [comment]
Looks like the UI tests failed.  ( 

But can't review this particular issue because we need to perform Update to test it. So lets merge and test

**Pull request closed without merging**
