### PR TITLE
PMM-4907: aws setup wizard

### PR DESCRIPTION
**Pull request by lunaticusgreen**
https://github.com/percona/pmm-server/pull/185

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-574-f09eed4
client docker - perconalab/pmm-client-fb:PR-574-f09eed4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-574-f09eed4.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-574-ad29569
client docker - perconalab/pmm-client-fb:PR-574-ad29569
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-574-ad29569.tar.gz

**Comment by AlekSi** [comment]
@rnovikovP IIRC, you wanted to check the new UI

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server/pull/185 merged

**Pull request closed without merging**
