### PR TITLE
PMM-9413 Deadlock during agent addition/removal in pmm-managed

### PR DESCRIPTION
**Pull request by floatinginbits**
[PMM-9413](https://jira.percona.com/browse/PMM-9413) : A deadlock occurs when a goroutine waits to acquire an already acquired lock. This bug breaks functionality for adding or removing agents from PMM server.

This PR generates a feature build for fix to above bug.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2291-f7a45ec
client docker - perconalab/pmm-client-fb:PR-2291-f7a45ec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2291-f7a45ec.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2291-f7a45ec&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2291-f7a45ec.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/11570/

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm-managed/pull/982

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2291-1fcbcda
client docker - perconalab/pmm-client-fb:PR-2291-1fcbcda
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2291-1fcbcda.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2291-1fcbcda&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2291-1fcbcda.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9331/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/12489/

**Comment by floatinginbits** [comment]
Feature tested by QA.

**Pull request closed without merging**
