### PR TITLE
PMM-9407 Add queries.yaml to debian package to postgres medium-resolution path

### PR DESCRIPTION
**Pull request by anton-bystrov**
[PMM-9407](https://jira.percona.com/browse/PMM-9407)
Add queries.yaml to path postgresql/medium-resolution in debian package.
Before:
изображение
After:
изображение

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2271-a200e38
client docker - perconalab/pmm-client-fb:PR-2271-a200e38
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2271-a200e38.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2271-a200e38&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2271-a200e38.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/11475/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2271-56211e6
client docker - perconalab/pmm-client-fb:PR-2271-56211e6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2271-56211e6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2271-56211e6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2271-56211e6.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/8460/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/11477/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2271-9a9e45f
client docker - perconalab/pmm-client-fb:PR-2271-9a9e45f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2271-9a9e45f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2271-9a9e45f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2271-9a9e45f.tar.gz

**Review by denisok — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
