### PR TITLE
PMM-3165 Remove Consul from PMM Server

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by AlekSi** [comment]
Waiting for Jenkins…

**Comment by AlekSi** [comment]
Anyway, pushing it out of -pre-0301. It is getting late already. :)

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-update/pull/17  and  https://github.com/percona/pmm-server/pull/119 merged. Should we merge this one?

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-177-621cf2e
client docker - perconalab/pmm-client-fb:PR-177-621cf2e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-177-621cf2e.tar.gz

**Pull request merged**
