### PR TITLE
PMM-7366 Feature build

### PR DESCRIPTION
**Pull request by artemgavrilov**
[PMM-7366](https://jira.percona.com/browse/PMM-7366)

- [ ] https://github.com/percona/pmm-managed/pull/657
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/186

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-fa3825a
client docker - perconalab/pmm-client-fb:PR-1493-fa3825a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-fa3825a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-fa3825a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-fa3825a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-fa3825a
client docker - perconalab/pmm-client-fb:PR-1493-fa3825a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-fa3825a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-fa3825a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-fa3825a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-b1697b8
client docker - perconalab/pmm-client-fb:PR-1493-b1697b8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-b1697b8.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-b1697b8&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-b1697b8.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-fa3825a
client docker - perconalab/pmm-client-fb:PR-1493-fa3825a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-fa3825a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-fa3825a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-fa3825a.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5981/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5398/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6947/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5983/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5400/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6950/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-1fe1328
client docker - perconalab/pmm-client-fb:PR-1493-1fe1328
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-1fe1328.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-1fe1328&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-1fe1328.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5998/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5415/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6969/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-b1aa569
client docker - perconalab/pmm-client-fb:PR-1493-b1aa569
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-b1aa569.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-b1aa569&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-b1aa569.tar.gz

**Comment by yurkovychv** [comment]
Having 2 failed tests like [here](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7023/tests) is expected. Please ignore those 2 failures.

**Comment by artemgavrilov** [comment]
> Having 2 failed tests like [here](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7023/tests) is expected. Please ignore those 2 failures.

Ok, thanks 👌

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6042/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5459/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7028/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-e90c147
client docker - perconalab/pmm-client-fb:PR-1493-e90c147
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-e90c147.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-e90c147&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-e90c147.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1493-68393b7
client docker - perconalab/pmm-client-fb:PR-1493-68393b7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-68393b7.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1493-68393b7&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1493-68393b7.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6052/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5469/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7039/

**Pull request closed without merging**
