### PR TITLE
PMM-8627 Reorganize API tests package

### PR DESCRIPTION
**Pull request by artemgavrilov**
[PMM-8627](https://jira.percona.com/browse/PMM-8627)

- [ ] https://github.com/percona/pmm-managed/pull/837

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2059-a99807c
client docker - perconalab/pmm-client-fb:PR-2059-a99807c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2059-a99807c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2059-a99807c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2059-a99807c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2059-99f2b1d
client docker - perconalab/pmm-client-fb:PR-2059-99f2b1d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2059-99f2b1d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2059-99f2b1d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2059-99f2b1d.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/7676/

**Comment by yurkovychv** [comment]
CLI tests failure is not related to changes in this FB.

**Pull request closed without merging**
