### PR TITLE
PMM-2607-Auto-adding-footer-to-PMM-demo

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-71-e388fb2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-71-e388fb2.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-71-e388fb2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-71-e388fb2.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-71-e388fb2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-71-e388fb2.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server/pull/77 merged

**Pull request closed without merging**
