### PR TITLE
PMM-12802-update-grafana-plugins (FB)

### PR DESCRIPTION
**Pull request by YashSartanpara1**
Custom branches: 
grafana-dashboards

### CODE REVIEW

**Comment by JNKPercona** [comment]
Server docker: perconalab/pmm-server-fb:PR-3560-3809b3c
Client docker: perconalab/pmm-client-fb:PR-3560-3809b3c
Client tarball: https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3560-3809b3c.tar.gz
Staging instance: https://pmm.cd.percona.com/job/pmm3-aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3560-3809b3c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3560-3809b3c.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed. Please check: https://pmm.cd.percona.com/job/pmm3-api-tests/209/

**Comment by puneet0191** [comment]
@YashSartanpara1 the FB looks very old, do you recommend to re-do a new one?

**Comment by YashSartanpara1** [comment]
> @YashSartanpara1 the FB looks very old, do you recommend to re-do a new one?

Sure please.

**Comment by JNKPercona** [comment]
Server docker: perconalab/pmm-server-fb:PR-3560-46f4553
Client docker: perconalab/pmm-client-fb:PR-3560-46f4553
Client tarball: https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3560-46f4553.tar.gz
Staging instance: https://pmm.cd.percona.com/job/pmm3-aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3560-46f4553&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3560-46f4553.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed. Please check: https://pmm.cd.percona.com/job/pmm3-api-tests/344/

**Pull request closed without merging**
