### PR TITLE
PMM-3256 Custom flags should overwrite default flags.

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-3256

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-d3db73f
client docker - perconalab/pmm-client-fb:PR-225-d3db73f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-d3db73f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-d3db73f
client docker - perconalab/pmm-client-fb:PR-225-d3db73f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-d3db73f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-d3db73f
client docker - perconalab/pmm-client-fb:PR-225-d3db73f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-d3db73f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-d3db73f
client docker - perconalab/pmm-client-fb:PR-225-d3db73f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-d3db73f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-d3db73f
client docker - perconalab/pmm-client-fb:PR-225-d3db73f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-d3db73f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-fa3e486
client docker - perconalab/pmm-client-fb:PR-225-fa3e486
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-fa3e486.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-225-fe2f30d
client docker - perconalab/pmm-client-fb:PR-225-fe2f30d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-225-fe2f30d.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-client/pull/198 merged

**Pull request closed without merging**
