### PR TITLE
PMM-2561 Feature build with Grafana5.1.X inside

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-41-457782f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-41-457782f.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-41-45ced38
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-41-45ced38.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-41-f5b9162
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-41-f5b9162.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-41-f5b9162
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-41-f5b9162.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server-packaging/pull/5 merged

**Pull request closed without merging**
