### PR TITLE
PMM-6013 change pmm repo default branch

### PR DESCRIPTION
**Pull request by nikita-b**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2091-60f44e3
client docker - perconalab/pmm-client-fb:PR-2091-60f44e3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2091-60f44e3.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2091-60f44e3&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2091-60f44e3.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/8242/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/10358/

**Review by BupycHuk — APPROVED** [review]

**Review by ademidoff — APPROVED** [review]
Thank you!

**Pull request merged**
