### PR TITLE
SAAS-104 Prometheus metrics for STT

### PR DESCRIPTION
**Pull request by palash25**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-904-4c53326
client docker - perconalab/pmm-client-fb:PR-904-4c53326
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-904-4c53326.tar.gz

**Comment by AlekSi** [comment]
@palash25 Please add API tests branch too – it will be tested on CI

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-904-3341911
client docker - perconalab/pmm-client-fb:PR-904-3341911
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-904-3341911.tar.gz

**Comment by palash25** [comment]
>  @palash25 Please add API tests branch too – it will be tested on CI

done

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-904-1093223
client docker - perconalab/pmm-client-fb:PR-904-1093223
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-904-1093223.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-904-bcf48e0
client docker - perconalab/pmm-client-fb:PR-904-bcf48e0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-904-bcf48e0.tar.gz

**Comment by palash25** [comment]
UI tests are failing

**Comment by yurkovychv** [comment]
The UI tests were reran and the job was green.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-904-6360f05
client docker - perconalab/pmm-client-fb:PR-904-6360f05
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-904-6360f05.tar.gz

**Comment by AlekSi** [comment]
@palash25 Please don't forget to update FB once there are changes in branches, or some branches were merged.

@yurkovychv It is QA's responsibility to ensure that we do that, not mine. Please track that.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-904-458c773
client docker - perconalab/pmm-client-fb:PR-904-458c773
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-904-458c773.tar.gz

**Comment by yurkovychv** [comment]
failed UI tests are not related to this PR. Closing

**Pull request closed without merging**
