### PR TITLE
[FB] PMM-6256 Fixed MongoDB explain

### PR DESCRIPTION
**Pull request by percona-csalguero**
- [ ] https://github.com/percona/percona-toolkit/pull/459
- [ ] https://github.com/percona/pmm-agent/pull/176

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-2035162
client docker - perconalab/pmm-client-fb:PR-954-2035162
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-2035162.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-38ca738
client docker - perconalab/pmm-client-fb:PR-954-38ca738
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-38ca738.tar.gz

**Comment by AlekSi** [comment]
Please ensure that FB is rewinded when ticket hits QA

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-86dd445
client docker - perconalab/pmm-client-fb:PR-954-86dd445
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-86dd445.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-0d28d4c
client docker - perconalab/pmm-client-fb:PR-954-0d28d4c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-0d28d4c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-81d83ab
client docker - perconalab/pmm-client-fb:PR-954-81d83ab
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-81d83ab.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-fe94b1c
client docker - perconalab/pmm-client-fb:PR-954-fe94b1c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-fe94b1c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-1a6451a
client docker - perconalab/pmm-client-fb:PR-954-1a6451a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-1a6451a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-954-a5bdc80
client docker - perconalab/pmm-client-fb:PR-954-a5bdc80
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-954-a5bdc80.tar.gz

**Pull request closed without merging**
