### PR TITLE
PMM-6272 New settings page

### PR DESCRIPTION
**Pull request by tiagomotasantos**
https://github.com/percona/grafana-dashboards/pull/868

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-976-65f4a6c
client docker - perconalab/pmm-client-fb:PR-976-65f4a6c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-976-65f4a6c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-976-361818f
client docker - perconalab/pmm-client-fb:PR-976-361818f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-976-361818f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-976-633ebb6
client docker - perconalab/pmm-client-fb:PR-976-633ebb6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-976-633ebb6.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-976-20958be
client docker - perconalab/pmm-client-fb:PR-976-20958be
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-976-20958be.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-976-f77ad8a
client docker - perconalab/pmm-client-fb:PR-976-f77ad8a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-976-f77ad8a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-976-250b3cd
client docker - perconalab/pmm-client-fb:PR-976-250b3cd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-976-250b3cd.tar.gz

**Comment by atymchuk** [comment]
Closing this in favour of #992

**Pull request closed without merging**
