### PR TITLE
PMM-4470 test mongodb_exporter update

### PR DESCRIPTION
**Pull request by rnovikovP**
PR  for test.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-364-aca8d4b
client docker - perconalab/pmm-client-fb:PR-364-aca8d4b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-364-aca8d4b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-364-3fe501a
client docker - perconalab/pmm-client-fb:PR-364-3fe501a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-364-3fe501a.tar.gz

**Comment by puneet0191** [comment]
@rnovikovP rewind submodules

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-364-1da491c
client docker - perconalab/pmm-client-fb:PR-364-1da491c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-364-1da491c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-364-83b2341
client docker - perconalab/pmm-client-fb:PR-364-83b2341
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-364-83b2341.tar.gz

**Pull request closed without merging**
