### PR TITLE
PMM-7 FB package test names update

### PR DESCRIPTION
**Pull request by vyarosh**
- Percona-QA/package-testing/pull/636

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3538-864fd76
client docker - perconalab/pmm-client-fb:PR-3538-864fd76
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-864fd76.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3538-864fd76&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-864fd76.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14896/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3538-84c3602
client docker - perconalab/pmm-client-fb:PR-3538-84c3602
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-84c3602.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3538-84c3602&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-84c3602.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14897/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3538-8e9d1bc
client docker - perconalab/pmm-client-fb:PR-3538-8e9d1bc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-8e9d1bc.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3538-8e9d1bc&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-8e9d1bc.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14901/

**Comment by vyarosh** [comment]
Target is the following check titles in list: 

More details in FB job: https://github.com/Percona-Lab/pmm-submodules/actions/runs/7834431133/job/21377989293

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3538-5a4ea86
client docker - perconalab/pmm-client-fb:PR-3538-5a4ea86
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-5a4ea86.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3538-5a4ea86&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3538-5a4ea86.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14903/

**Review by saikumar-vs — APPROVED** [review]

**Review by puneet0191 — APPROVED** [review]

**Pull request merged**
