### PR TITLE
PMM-12622 added pmm-server only tests and quiet mode

### PR DESCRIPTION
**Pull request by vyarosh**
https://jira.percona.com/browse/PMM-12622 
Added Server only tests for only relevant version

### CODE REVIEW

**Comment by JNKPercona** [comment]
PMM3 Submodules skipped

**Comment by JNKPercona** [comment]
PMM3 Submodules skipped

**Comment by JNKPercona** [comment]
PMM3 Submodules skipped

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3458-43b88e7
client docker - perconalab/pmm-client-fb:PR-3458-43b88e7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-43b88e7.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3458-43b88e7&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-43b88e7.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14584/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3458-56a0954
client docker - perconalab/pmm-client-fb:PR-3458-56a0954
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-56a0954.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3458-56a0954&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-56a0954.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3458-2021f98
client docker - perconalab/pmm-client-fb:PR-3458-2021f98
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-2021f98.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3458-2021f98&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-2021f98.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14586/

**Review by yurkovychv — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3458-a9682e1
client docker - perconalab/pmm-client-fb:PR-3458-a9682e1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-a9682e1.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3458-a9682e1&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3458-a9682e1.tar.gz

**Pull request merged**
