### PR TITLE
PMM-7521 Alert templates pagination

### PR DESCRIPTION
**Pull request by Dasio**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1556-3918f1f
client docker - perconalab/pmm-client-fb:PR-1556-3918f1f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1556-3918f1f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1556-3918f1f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1556-3918f1f.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6161/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5578/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7185/

**Comment by yurkovychv** [comment]
please ignore [this](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7185/tests) failing test

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1556-2710bf6
client docker - perconalab/pmm-client-fb:PR-1556-2710bf6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1556-2710bf6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1556-2710bf6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1556-2710bf6.tar.gz

**Pull request closed without merging**
