### PR TITLE
PMM-5182 Add PMM Server Summary information to logs.zip.

### PR DESCRIPTION
**Pull request by AlekSi**
- [ ] https://github.com/percona/pmm-managed/pull/324
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/78

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-650-171ad41
client docker - perconalab/pmm-client-fb:PR-650-171ad41
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-650-171ad41.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-650-4304cab
client docker - perconalab/pmm-client-fb:PR-650-4304cab
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-650-4304cab.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-650-77cd872
client docker - perconalab/pmm-client-fb:PR-650-77cd872
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-650-77cd872.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-650-8bb3e37
client docker - perconalab/pmm-client-fb:PR-650-8bb3e37
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-650-8bb3e37.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-650-64e0c07
client docker - perconalab/pmm-client-fb:PR-650-64e0c07
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-650-64e0c07.tar.gz

**Comment by AlekSi** [comment]
Will be continued at #710.

**Pull request closed without merging**
