### PR TITLE
PMM-6766 remove qan app1

### PR DESCRIPTION
**Pull request by atymchuk**
Relevant PRs:
- https://github.com/percona/pmm-server/pull/244
- https://github.com/percona/pmm-server-packaging/pull/196
- https://github.com/Percona-Lab/jenkins-pipelines/pull/745
- https://github.com/Percona-Lab/percona-images/pull/97
- https://github.com/percona/pmm/pull/658
- https://github.com/percona/grafana-dashboards/pull/1097
- https://github.com/percona/pmm-update/pull/116
- https://github.com/percona/pmm-managed/pull/668

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1429-06c4a25
client docker - perconalab/pmm-client-fb:PR-1429-06c4a25
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-06c4a25.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1429-06c4a25&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-06c4a25.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1429-06c4a25
client docker - perconalab/pmm-client-fb:PR-1429-06c4a25
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-06c4a25.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1429-06c4a25&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-06c4a25.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5661/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5074/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6534/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5660/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5073/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6533/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1429-a3aee2d
client docker - perconalab/pmm-client-fb:PR-1429-a3aee2d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-a3aee2d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1429-a3aee2d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-a3aee2d.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5896/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5313/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6828/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1429-15e639c
client docker - perconalab/pmm-client-fb:PR-1429-15e639c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-15e639c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1429-15e639c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1429-15e639c.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5922/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5339/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6874/

**Comment by atymchuk** [comment]
Closing, created a new one https://github.com/Percona-Lab/pmm-submodules/pull/1515

**Pull request closed without merging**
