### PR TITLE
PMM-6268 upgrade angular to v10, CVE fix

### PR DESCRIPTION
**Pull request by atymchuk**
- [x] https://github.com/percona/pmm-server/pull/220
- [x] https://github.com/percona/pmm-server-packaging/pull/169

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-9da75d5
client docker - perconalab/pmm-client-fb:PR-959-9da75d5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-9da75d5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-572e706
client docker - perconalab/pmm-client-fb:PR-959-572e706
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-572e706.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-6d4dcb1
client docker - perconalab/pmm-client-fb:PR-959-6d4dcb1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-6d4dcb1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-3c4083f
client docker - perconalab/pmm-client-fb:PR-959-3c4083f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-3c4083f.tar.gz

**Review by EvgeniyPatlan — DISMISSED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-b0a466b
client docker - perconalab/pmm-client-fb:PR-959-b0a466b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-b0a466b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-b0a466b
client docker - perconalab/pmm-client-fb:PR-959-b0a466b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-b0a466b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-b0a466b
client docker - perconalab/pmm-client-fb:PR-959-b0a466b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-b0a466b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-6b94e6c
client docker - perconalab/pmm-client-fb:PR-959-6b94e6c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-6b94e6c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-959-36b2cd7
client docker - perconalab/pmm-client-fb:PR-959-36b2cd7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-959-36b2cd7.tar.gz

**Pull request closed without merging**
