### PR TITLE
PMM-2182 Prometheus 2

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-0ce65c9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-0ce65c9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-b87d5fd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-b87d5fd.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-c06ecf9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-c06ecf9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-af624fc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-af624fc.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-ee5018c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-ee5018c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-31ab19e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-31ab19e.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-32b2edb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-32b2edb.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-b6b52b9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-b6b52b9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-af6cc5c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-af6cc5c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-af6cc5c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-af6cc5c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-d37ee27
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-d37ee27.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-6f4e7e2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-6f4e7e2.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-183538c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-183538c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-a31403e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-a31403e.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-16-a31403e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-16-a31403e.tar.gz

**Comment by delgod** [comment]
merged

**Pull request closed without merging**
