### PR TITLE
PMM-11345 PMM-11272 Security advisors section Create FB FE + BE

### PR DESCRIPTION
**Pull request by filipmikes1**
https://jira.percona.com/browse/PMM-11345
https://jira.percona.com/browse/PMM-11272

- [ ] https://github.com/percona/pmm/pull/1684
- [ ] https://github.com/percona-platform/grafana/pull/604

### CODE REVIEW

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-8faa113
client docker - perconalab/pmm-client-fb:PR-3077-8faa113
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-8faa113.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-8faa113&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-8faa113.tar.gz

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-f3aa18d
client docker - perconalab/pmm-client-fb:PR-3077-f3aa18d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-f3aa18d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-f3aa18d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-f3aa18d.tar.gz

**Comment by VoK0** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/3077#issuecomment-1443778153 I've tried to test this FB 
image
I don't see even a login page at all i am simply redirected to the dashboard page but since I am not authenticated i cannot perform any action cause i will received unauthenticated request error.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-f3aa18d
client docker - perconalab/pmm-client-fb:PR-3077-f3aa18d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-f3aa18d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-f3aa18d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-f3aa18d.tar.gz

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-f3aa18d
client docker - perconalab/pmm-client-fb:PR-3077-f3aa18d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-f3aa18d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-f3aa18d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-f3aa18d.tar.gz

**Comment by VoK0** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/3077#issuecomment-1448378751
Broken routing from Advisors dashboad -> Advisors check details

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-0e34f56
client docker - perconalab/pmm-client-fb:PR-3077-0e34f56
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-0e34f56.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-0e34f56&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-0e34f56.tar.gz

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by VoK0** [comment]
Features Verified on this FB https://github.com/Percona-Lab/pmm-submodules/pull/3077#issuecomment-1451724359
Since they are some changes in https://github.com/Percona-Lab/pmm-submodules/pull/3077#issuecomment-1451968422 I need to recheck tomorrow once FE & BE will be in sync
Please Move to my Que once everything is ready for review.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-0e34f56
client docker - perconalab/pmm-client-fb:PR-3077-0e34f56
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-0e34f56.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-0e34f56&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-0e34f56.tar.gz

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3077-0e34f56
client docker - perconalab/pmm-client-fb:PR-3077-0e34f56
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-0e34f56.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3077-0e34f56&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3077-0e34f56.tar.gz

**Comment by VoK0** [comment]
Retested as promised https://github.com/Percona-Lab/pmm-submodules/pull/3077#issuecomment-1453270860

**Pull request closed without merging**
