### PR TITLE
PMM-10036-migrate-to-monorepo (FB)

### PR DESCRIPTION
**Pull request by nikita-b**
Custom branches: 
pmm

### CODE REVIEW

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1056

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1056

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2650-298267b
client docker - perconalab/pmm-client-fb:PR-2650-298267b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2650-298267b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2650-298267b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2650-298267b.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/19455/

**Review by ademidoff — APPROVED** [review]

**Pull request merged**
