### PR TITLE
SAAS-321 Merge PERCONA_TEST_XXX_HOST environment variables

### PR DESCRIPTION
**Pull request by yurkovychv**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-21ddf86
client docker - perconalab/pmm-client-fb:PR-1113-21ddf86
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-21ddf86.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-21ddf86
client docker - perconalab/pmm-client-fb:PR-1113-21ddf86
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-21ddf86.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-7037c5a
client docker - perconalab/pmm-client-fb:PR-1113-7037c5a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-7037c5a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-7037c5a
client docker - perconalab/pmm-client-fb:PR-1113-7037c5a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-7037c5a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-7037c5a
client docker - perconalab/pmm-client-fb:PR-1113-7037c5a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-7037c5a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-7694605
client docker - perconalab/pmm-client-fb:PR-1113-7694605
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-7694605.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-203a990
client docker - perconalab/pmm-client-fb:PR-1113-203a990
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-203a990.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-203a990
client docker - perconalab/pmm-client-fb:PR-1113-203a990
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-203a990.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-203a990
client docker - perconalab/pmm-client-fb:PR-1113-203a990
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-203a990.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-203a990
client docker - perconalab/pmm-client-fb:PR-1113-203a990
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-203a990.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1113-0ae1f92
client docker - perconalab/pmm-client-fb:PR-1113-0ae1f92
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1113-0ae1f92.tar.gz

**Comment by yurkovychv** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/1121

**Pull request closed without merging**
