### PR TITLE
PMM-7530 Duplicate alerts in postgres

### PR DESCRIPTION
**Pull request by Dasio**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1511-34e2b1f
client docker - perconalab/pmm-client-fb:PR-1511-34e2b1f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1511-34e2b1f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1511-34e2b1f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1511-34e2b1f.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5965/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5382/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6930/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1511-b3d3e38
client docker - perconalab/pmm-client-fb:PR-1511-b3d3e38
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1511-b3d3e38.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1511-b3d3e38&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1511-b3d3e38.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5973/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5390/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6939/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1511-3653ed6
client docker - perconalab/pmm-client-fb:PR-1511-3653ed6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1511-3653ed6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1511-3653ed6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1511-3653ed6.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6039/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5456/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7025/

**Comment by Dasio** [comment]
Failed tests are not related to this PR. Please ignore it

**Pull request closed without merging**
