### PR TITLE
PMM-12921 switch tarball test to pmm-qa

### PR DESCRIPTION
**Pull request by vyarosh**
https://jira.percona.com/browse/PMM-12921

### CODE REVIEW

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14962/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3551-662584b
client docker - perconalab/pmm-client-fb:PR-3551-662584b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3551-662584b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3551-662584b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3551-662584b.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14965/

**Comment by vyarosh** [comment]
https://github.com/Percona-Lab/pmm-submodules/actions/runs/7974265303

**Review by saikumar-vs — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3551-662584b
client docker - perconalab/pmm-client-fb:PR-3551-662584b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3551-662584b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3551-662584b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3551-662584b.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/14972/

**Pull request merged**
