### PR TITLE
PMM-6756 Use Go 1.15

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1292-d556f3e
client docker - perconalab/pmm-client-fb:PR-1292-d556f3e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1292-d556f3e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1292-d556f3e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1292-d556f3e.tar.gz

**Review by Sudokamikaze — DISMISSED** [review]

**Comment by AlekSi** [comment]
https://groups.google.com/u/1/g/golang-announce/c/KvrRblbXp_w

Will wait until tomorrow

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1292-3aa4ced
client docker - perconalab/pmm-client-fb:PR-1292-3aa4ced
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1292-3aa4ced.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1292-3aa4ced&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1292-3aa4ced.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1292-8331ab0
client docker - perconalab/pmm-client-fb:PR-1292-8331ab0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1292-8331ab0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1292-8331ab0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1292-8331ab0.tar.gz

**Review by atymchuk — APPROVED** [review]

**Review by EvgeniyPatlan — APPROVED** [review]

**Pull request merged**
