### PR TITLE
SAAS-93-Configurable-Action-Timeout FB

### PR DESCRIPTION
**Pull request by palash25**
- [Ticket](https://jira.percona.com/browse/SAAS-93)

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1037-b224b27
client docker - perconalab/pmm-client-fb:PR-1037-b224b27
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1037-b224b27.tar.gz

**Comment by AlekSi** [comment]
`pmm` repo PR was merged

**Comment by palash25** [comment]
> pmm repo PR was merged

Updating the FB in a min

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1037-4981ebe
client docker - perconalab/pmm-client-fb:PR-1037-4981ebe
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1037-4981ebe.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1037-8bdfb0b
client docker - perconalab/pmm-client-fb:PR-1037-8bdfb0b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1037-8bdfb0b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1037-bbc363b
client docker - perconalab/pmm-client-fb:PR-1037-bbc363b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1037-bbc363b.tar.gz

**Pull request closed without merging**
