### PR TITLE
SAAS-67 API for manual checks execution

### PR DESCRIPTION
**Pull request by artemgavrilov**
- https://jira.percona.com/browse/SAAS-67

- [ ] https://github.com/percona/pmm-managed/pull/392
- [x] https://github.com/percona/pmm/pull/529

- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/99

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-857-e2e38ec
client docker - perconalab/pmm-client-fb:PR-857-e2e38ec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-857-e2e38ec.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-857-f0365fa
client docker - perconalab/pmm-client-fb:PR-857-f0365fa
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-857-f0365fa.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-857-4a34f55
client docker - perconalab/pmm-client-fb:PR-857-4a34f55
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-857-4a34f55.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-857-b87d691
client docker - perconalab/pmm-client-fb:PR-857-b87d691
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-857-b87d691.tar.gz

**Comment by AlekSi** [comment]
@artemgavrilov It should also include pmm and pmm-api-tests repos

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-857-d9098f7
client docker - perconalab/pmm-client-fb:PR-857-d9098f7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-857-d9098f7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-857-92e9ce5
client docker - perconalab/pmm-client-fb:PR-857-92e9ce5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-857-92e9ce5.tar.gz

**Pull request closed without merging**
