### PR TITLE
PMM-7296: FB ListAlertRules pagination

### PR DESCRIPTION
**Pull request by oter**
https://jira.percona.com/browse/PMM-7296

https://github.com/percona/pmm/pull/662
https://github.com/percona/pmm-managed/pull/642
https://github.com/Percona-Lab/pmm-api-tests/pull/180

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-71f0938
client docker - perconalab/pmm-client-fb:PR-1457-71f0938
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-71f0938.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-71f0938&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-71f0938.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5749/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5164/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6643/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-71f0938
client docker - perconalab/pmm-client-fb:PR-1457-71f0938
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-71f0938.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-71f0938&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-71f0938.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-b6848cf
client docker - perconalab/pmm-client-fb:PR-1457-b6848cf
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-b6848cf.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-b6848cf&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-b6848cf.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5783/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5199/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6686/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5784/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5200/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6687/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-5f3f74c
client docker - perconalab/pmm-client-fb:PR-1457-5f3f74c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-5f3f74c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-5f3f74c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-5f3f74c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-5f3f74c
client docker - perconalab/pmm-client-fb:PR-1457-5f3f74c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-5f3f74c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-5f3f74c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-5f3f74c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-15797df
client docker - perconalab/pmm-client-fb:PR-1457-15797df
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-15797df.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-15797df&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-15797df.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6006/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5423/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6981/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-da5311a
client docker - perconalab/pmm-client-fb:PR-1457-da5311a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-da5311a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-da5311a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-da5311a.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6040/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5457/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7026/

**Comment by yurkovychv** [comment]
Please ignore failed UI tests. 2 failed tests are not related to this FB. Fixing those right now

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1457-14e6627
client docker - perconalab/pmm-client-fb:PR-1457-14e6627
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-14e6627.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1457-14e6627&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1457-14e6627.tar.gz

**Pull request closed without merging**
