### PR TITLE
PMM-7497 fix insufficient rights message

### PR DESCRIPTION
**Pull request by nicolalamacchia**
https://github.com/percona/grafana-dashboards/pull/1156

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1524-ebb8496
client docker - perconalab/pmm-client-fb:PR-1524-ebb8496
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-ebb8496.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1524-ebb8496&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-ebb8496.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1524-d54e5a9
client docker - perconalab/pmm-client-fb:PR-1524-d54e5a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-d54e5a9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1524-d54e5a9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-d54e5a9.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6014/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5431/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6992/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6015/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5432/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6993/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1524-301bb60
client docker - perconalab/pmm-client-fb:PR-1524-301bb60
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-301bb60.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1524-301bb60&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-301bb60.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1524-c3a6054
client docker - perconalab/pmm-client-fb:PR-1524-c3a6054
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-c3a6054.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1524-c3a6054&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-c3a6054.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6028/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5445/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7010/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6030/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5447/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7013/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1524-c872053
client docker - perconalab/pmm-client-fb:PR-1524-c872053
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-c872053.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1524-c872053&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1524-c872053.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6033/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5450/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7018/

**Comment by yurkovychv** [comment]
created new PR https://github.com/Percona-Lab/pmm-submodules/pull/1530

**Pull request closed without merging**
