### PR TITLE
PMM-7653 Fixed release 2.15.1 with mongodb_exporter 0.20.3

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1594-0f760b6
client docker - perconalab/pmm-client-fb:PR-1594-0f760b6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1594-0f760b6.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1594-0f760b6&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1594-0f760b6.tar.gz

**Review by rnovikovP — DISMISSED** [review]

**Review by denisok — DISMISSED** [review]

**Comment by puneet0191** [comment]
@denisok @rnovikovP where is FB for this PR, could you please point me

**Comment by denisok** [comment]
man... now it rewinded with new changes from mysqld exporter ... as we use master for it.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1594-76e545b
client docker - perconalab/pmm-client-fb:PR-1594-76e545b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1594-76e545b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1594-76e545b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1594-76e545b.tar.gz

**Comment by rnovikovP** [comment]
> man... now it rewinded with new changes from mysqld exporter ... as we use master for it.

this  is expected

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7345/

**Review by denisok — DISMISSED** [review]
OK, we would add mysqld new changes into 2.15.1

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1594-c307627
client docker - perconalab/pmm-client-fb:PR-1594-c307627
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1594-c307627.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1594-c307627&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1594-c307627.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7355/

**Review by denisok — APPROVED** [review]

**Comment by puneet0191** [comment]
This looks fine for all tests, have run seperately and verified. We can create a new PR with only branch change and merge it

**Comment by denisok** [comment]
> This looks fine for all tests, have run seperately and verified. We can create a new PR with only branch change and merge it

#1589 maybe we just merge it ?

**Comment by denisok** [comment]
> > This looks fine for all tests, have run seperately and verified. We can create a new PR with only branch change and merge it
> 
> #1589 maybe we just merge it ?

nope, that also has sub modules changes. We need only code change.

**Comment by percona-csalguero** [comment]
Closing in favor of https://github.com/Percona-Lab/pmm-submodules/pull/1605

**Pull request closed without merging**
