### PR TITLE
PMM-2485 Custom singlestat panel

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-2485

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-37-1fc1b22
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-37-1fc1b22.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-37-babe24f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-37-babe24f.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-37-babe24f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-37-babe24f.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/196 merged

**Pull request closed without merging**
