### PR TITLE
PMM-5438: alertmanager tooltip

### PR DESCRIPTION
**Pull request by lunaticusgreen**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-3872a78
client docker - perconalab/pmm-client-fb:PR-689-3872a78
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-3872a78.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-e702e92
client docker - perconalab/pmm-client-fb:PR-689-e702e92
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-e702e92.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-277f96e
client docker - perconalab/pmm-client-fb:PR-689-277f96e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-277f96e.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-7ec73c0
client docker - perconalab/pmm-client-fb:PR-689-7ec73c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-7ec73c0.tar.gz

**Comment by puneet0191** [comment]
@lunaticusgreen this could be a great example, to fix UI tests also with this FB, you just need to submodules, as I see UI tests are failing because of change in text for Alert Manager is causing that, the test is expecting to find `AlertManager` while the new text is `Alertmanager`

**Comment by puneet0191** [comment]
The file that needs to be changed, https://github.com/percona/pmm-qa/blob/master/tests/pages/pmmSettingsPage.js

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-4733f0b
client docker - perconalab/pmm-client-fb:PR-689-4733f0b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-4733f0b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-35e5089
client docker - perconalab/pmm-client-fb:PR-689-35e5089
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-35e5089.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-10fc512
client docker - perconalab/pmm-client-fb:PR-689-10fc512
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-10fc512.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-689-97c1934
client docker - perconalab/pmm-client-fb:PR-689-97c1934
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-689-97c1934.tar.gz

**Pull request closed without merging**
