### PR TITLE
PMM-5700 fix minimist cve

### PR DESCRIPTION
**Pull request by atymchuk**
- [x] https://github.com/percona/pmm-server/pull/204
- [x] https://github.com/percona/qan-app/pull/384

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-781-f46e6bd
client docker - perconalab/pmm-client-fb:PR-781-f46e6bd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-781-f46e6bd.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-781-be27a75
client docker - perconalab/pmm-client-fb:PR-781-be27a75
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-781-be27a75.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-781-016aef4
client docker - perconalab/pmm-client-fb:PR-781-016aef4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-781-016aef4.tar.gz

**Comment by atymchuk** [comment]
Tested and closed.

**Pull request closed without merging**
