### PR TITLE
PMM-2304 New Dashboard System Compare Servers

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-33-62ce12c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-33-62ce12c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-33-62ce12c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-33-62ce12c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-33-62ce12c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-33-62ce12c.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/160 merged

**Pull request closed without merging**
