### PR TITLE
PMM-9749 PGSM settings column data type change.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**
https://jira.percona.com/browse/PMM-9749

- [ ] Links to other linked pull requests.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2407-3aed9ad
client docker - perconalab/pmm-client-fb:PR-2407-3aed9ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2407-3aed9ad.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2407-3aed9ad&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2407-3aed9ad.tar.gz

**Comment by JiriCtvrtka** [comment]
API test is not failed, it just not sent response properly.

See: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-api-tests/detail/pmm2-api-tests/9515/pipeline/
All green.

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9515/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/13221/

**Comment by JiriCtvrtka** [comment]
UI test fails are related to MySQL.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2407-3aed9ad
client docker - perconalab/pmm-client-fb:PR-2407-3aed9ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2407-3aed9ad.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2407-3aed9ad&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2407-3aed9ad.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9521/

**Pull request closed without merging**
