### PR TITLE
PMM-10156-second-iteration-home-dashboard (FB)

### PR DESCRIPTION
**Pull request by anton-bystrov**
Custom branches: 
grafana-dashboards

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2800-a22c5a9
client docker - perconalab/pmm-client-fb:PR-2800-a22c5a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2800-a22c5a9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2800-a22c5a9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2800-a22c5a9.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/22933/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2800-ead9e09
client docker - perconalab/pmm-client-fb:PR-2800-ead9e09
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2800-ead9e09.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2800-ead9e09&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2800-ead9e09.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/22935/

**Comment by ErikaDoniecova** [comment]
PMM UI test Matrix went through without new failures https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/1094/pipeline/19

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2800-555bc95
client docker - perconalab/pmm-client-fb:PR-2800-555bc95
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2800-555bc95.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2800-555bc95&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2800-555bc95.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/22963/

**Comment by ErikaDoniecova** [comment]
PMM UI tests matrix pipeline went through without new failures https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/1095/pipeline/19

**Pull request closed without merging**
