### PR TITLE
[FB] PMM-6120 Golang 1.14

### PR DESCRIPTION
**Pull request by Sevlin**
Golang 1.14.4

Closed in favor of https://github.com/Percona-Lab/pmm-submodules/pull/918

### CODE REVIEW

**Comment by AlekSi** [comment]
https://github.com/Percona-Lab/pmm-submodules/blob/7f3fbf5a7f7ad1529ff6d495aeaaa0475d23021a/build/bin/build-client-packages#L540

Let's remove it if it is not actually used, or add a comment to both places that they should be synced otherwise.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-747d68a
client docker - perconalab/pmm-client-fb:PR-900-747d68a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-747d68a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-747d68a
client docker - perconalab/pmm-client-fb:PR-900-747d68a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-747d68a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-e564a9f
client docker - perconalab/pmm-client-fb:PR-900-e564a9f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-e564a9f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-e564a9f
client docker - perconalab/pmm-client-fb:PR-900-e564a9f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-e564a9f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-d350781
client docker - perconalab/pmm-client-fb:PR-900-d350781
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-d350781.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-32ba912
client docker - perconalab/pmm-client-fb:PR-900-32ba912
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-32ba912.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-900-32ba912
client docker - perconalab/pmm-client-fb:PR-900-32ba912
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-900-32ba912.tar.gz

**Pull request closed without merging**
