### PR TITLE
SAAS-125 Send EndsAt with alerts to auto-resolve them

### PR DESCRIPTION
**Pull request by AlekSi**
- [ ] https://github.com/percona/pmm-managed/pull/405
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/114

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-e510676
client docker - perconalab/pmm-client-fb:PR-925-e510676
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-e510676.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-d5f8926
client docker - perconalab/pmm-client-fb:PR-925-d5f8926
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-d5f8926.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-b841e08
client docker - perconalab/pmm-client-fb:PR-925-b841e08
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-b841e08.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-5ec9028
client docker - perconalab/pmm-client-fb:PR-925-5ec9028
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-5ec9028.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-b793a81
client docker - perconalab/pmm-client-fb:PR-925-b793a81
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-b793a81.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-5fc129f
client docker - perconalab/pmm-client-fb:PR-925-5fc129f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-5fc129f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-8834212
client docker - perconalab/pmm-client-fb:PR-925-8834212
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-8834212.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-4455133
client docker - perconalab/pmm-client-fb:PR-925-4455133
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-4455133.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-925-fbf35ee
client docker - perconalab/pmm-client-fb:PR-925-fbf35ee
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-925-fbf35ee.tar.gz

**Comment by AlekSi** [comment]
Moved to https://github.com/Percona-Lab/pmm-submodules/pull/948

**Pull request closed without merging**
