### PR TITLE
PMM-2154 add dashboard for my sql command counters

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-34-38e62ec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-34-38e62ec.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-34-38e62ec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-34-38e62ec.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-34-1b9319c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-34-1b9319c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-34-2432373
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-34-2432373.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-34-0dd4273
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-34-0dd4273.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-34-0dd4273
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-34-0dd4273.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/184   merged

**Pull request closed without merging**
