### PR TITLE
PMM-4817 Add script for creating tags.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by AlekSi** [comment]
Sure enough, you will use bash for this ticket – when you will work on it.
In the meantime, I don't want to tag another release manually.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-594-ce7a456
client docker - perconalab/pmm-client-fb:PR-594-ce7a456
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-594-ce7a456.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-594-9384cd1
client docker - perconalab/pmm-client-fb:PR-594-9384cd1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-594-9384cd1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-594-4918751
client docker - perconalab/pmm-client-fb:PR-594-4918751
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-594-4918751.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-594-e46d571
client docker - perconalab/pmm-client-fb:PR-594-e46d571
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-594-e46d571.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-594-e46d571
client docker - perconalab/pmm-client-fb:PR-594-e46d571
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-594-e46d571.tar.gz

**Pull request merged**
