### PR TITLE
PMM-6632 Fix formulas for chart Virtual Memory Utilization

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1164-e4c433b
client docker - perconalab/pmm-client-fb:PR-1164-e4c433b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1164-e4c433b.tar.gz

**Comment by puneet0191** [comment]
I don't know why, but we get this on FB while trying to create an instance
image

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1164-8a6ca4a
client docker - perconalab/pmm-client-fb:PR-1164-8a6ca4a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1164-8a6ca4a.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4606/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3988/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5191/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1164-0c6a8f0
client docker - perconalab/pmm-client-fb:PR-1164-0c6a8f0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1164-0c6a8f0.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4645/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4027/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5235/

**Pull request closed without merging**
