### PR TITLE
PMM-10789 run fb tests

### PR DESCRIPTION
**Pull request by yurkovychv**
https://jira.percona.com/browse/PMM-0

- [ ] Links to relevant pull requests

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2978-17987aa
client docker - perconalab/pmm-client-fb:PR-2978-17987aa
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2978-17987aa.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2978-17987aa&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2978-17987aa.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2978-e046aba
client docker - perconalab/pmm-client-fb:PR-2978-e046aba
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2978-e046aba.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2978-e046aba&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2978-e046aba.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/26715/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2978-83c7687
client docker - perconalab/pmm-client-fb:PR-2978-83c7687
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2978-83c7687.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2978-83c7687&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2978-83c7687.tar.gz

**Comment by yurkovychv** [comment]
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-submodules/detail/PR-2978/21/pipeline

**Review by puneet0191 — APPROVED** [review]

**Pull request merged**
