### PR TITLE
PMM-7961 update exporter shared

### PR DESCRIPTION
**Pull request by denisok**
Updated exporter shared for mongodb_exporter

### CODE REVIEW

**Review by askomorokhov — DISMISSED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1900-523e252
client docker - perconalab/pmm-client-fb:PR-1900-523e252
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1900-523e252.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1900-523e252&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1900-523e252.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7430/

**Review by BupycHuk — DISMISSED** [review]

**Comment by denisok** [comment]
force pushed to remove rewind

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1900-ab7a99e
client docker - perconalab/pmm-client-fb:PR-1900-ab7a99e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1900-ab7a99e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1900-ab7a99e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1900-ab7a99e.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7436/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/9227/

**Comment by askomorokhov** [comment]
Locally API tests pass successfully (master branch on pmm-managed PMM-2.0)
This PR can be related https://github.com/Percona-Lab/pmm-api-tests/pull/225

```
als@mbp pmm-api-tests % git co master 
Already on 'master'
Your branch is up to date with 'origin/master'.
als@mbp pmm-api-tests %
als@mbp pmm-api-tests % make dev-test                                                                                                                                                                                                                         
go test -count=1 -p 1 -v ./... -pmm.server-insecure-tls                                                                                                                                                                                                       
?       github.com/Percona-Lab/pmm-api-tests    [no test files]                                                                                                                                                                                               
=== RUN   TestAzureDatabaseExporter                                                                                                                                                                                                                           
=== RUN   TestAzureDatabaseExporter/Basic                                                                                                                                                                                                                     
=== PAUSE TestAzureDatabaseExporter/Basic                                                                                                                                                                                                                     
=== RUN   TestAzureDatabaseExporter/AddNodeIDEmpty                                                                                                                                                                                                            
=== PAUSE TestAzureDatabaseExporter/AddNodeIDEmpty                                                                                                                                                                                                            
=== RUN   TestAzureDatabaseExporter/NotExistNodeID                                                                                                                                                                                                            
=== PAUSE TestAzureDatabaseExporter/NotExistNodeID                                                                                                                                                                                                            
=== RUN   TestAzureDatabaseExporter/NotExistPMMAgentID                                                                                                                                                                                                        
=== PAUSE TestAzureDatabaseExporter/NotExistPMMAgentID                                                                                                                                                                                                        
=== RUN   TestAzureDatabaseExporter/With_PushMetrics                                                                                                                                                                                                          
=== CONT  TestAzureDatabaseExporter/Basic                                                                                                                                                                                                                     
=== CONT  TestAzureDatabaseExporter/NotExistNodeID                                                                                                                                                                                                            
=== CONT  TestAzureDatabaseExporter/NotExistPMMAgentID                                                                                                                                                                                                        
=== CONT  TestAzureDatabaseExporter/AddNodeIDEmpty                                                                                                                                                                                                            
--- PASS: TestAzureDatabaseExporter (0.18s)                                                                                                                                                                                                                   
    --- PASS: TestAzureDatabaseExporter/With_PushMetrics (0.18s)                                                                                                                                                                                              
    --- PASS: TestAzureDatabaseExporter/NotExistPMMAgentID (0.04s)                                                                                                                                                                                            
    --- PASS: TestAzureDatabaseExporter/NotExistNodeID (0.06s)                                                                                                                                                                                                
    --- PASS: TestAzureDatabaseExporter/AddNodeIDEmpty (0.07s)                                                                                                                                                                                                
    --- PASS: TestAzureDatabaseExporter/Basic (0.11s)                  
.... 
=== CONT  TestVersion/managed/v1/version                                                                                                                                                                                                                      
    version_test.go:39: Response: {                                                                                                                                                                                                                           
          "version": "2.20.0",                                                                                                                                                                                                                                
          "server": {                                                                                                                                                                                                                                         
            "version": "2.20.0",                                                                                                                                                                                                                              
            "full_version": "2.20.0-59.2107060927.25a2df6.el7",                                                                                                                                                                                               
            "timestamp": "2021-07-06T09:27:50Z"                                                                                                                                                                                                               
          },                                                                                                                                                                                                                                                  
          "managed": {                                                                                                                                                                                                                                        
            "version": "2.20.0",                                                                                                                                                                                                                              
            "full_version": "85d8afbbd7db9482fcede7897eea14c700ea9a70",                                                                                                                                                                                       
            "timestamp": "2021-07-12T10:05:22Z"                                                                                                                                                                                                               
          },                                                                                                                                                                                                                                                  
          "distribution_method": "DOCKER"                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                     
=== CONT  TestVersion/v1/version                                                                                                                                                                                                                              
    version_test.go:39: Response: {                                                                                                                                                                                                                           
          "version": "2.20.0",                                                                                                                                                                                                                                
          "server": {                                                                                                                                                                                                                                         
            "version": "2.20.0",                                                                                                                                                                                                                              
            "full_version": "2.20.0-59.2107060927.25a2df6.el7",                                                                                                                                                                                               
            "timestamp": "2021-07-06T09:27:50Z"                                                                                                                                                                                                               
          },                                                                                                                                                                                                                                                  
          "managed": {                                                                                                                                                                                                                                        
            "version": "2.20.0",                                                                                                                                                                                                                              
            "full_version": "85d8afbbd7db9482fcede7897eea14c700ea9a70",                                                                                                                                                                                       
            "timestamp": "2021-07-12T10:05:22Z"                                                                                                                                                                                                               
          },                                                                                                                                                                                                                                                  
          "distribution_method": "DOCKER"                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                     
--- PASS: TestVersion (0.00s)                                                                                                                                                                                                                                 
    --- PASS: TestVersion/managed/v1/version (0.00s)                                                                                                                                                                                                          
    --- PASS: TestVersion/v1/version (0.00s)                                                                                                                                                                                                                  
PASS                                                                                                                                                                                                                                                          
ok      github.com/Percona-Lab/pmm-api-tests/server     13.076s                                                                                                                                                                                               
als@mbp pmm-api-tests %                                                                                                                                                                                                                                       
als@mbp pmm-api-tests %                                                                                                                                                                                                                                       
als@mbp pmm-api-tests %                
```

**Pull request merged**
