### PR TITLE
PMM-2837 fix image rendering

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-125-d09d4bc
client docker - perconalab/pmm-client-fb:PR-125-d09d4bc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-125-d09d4bc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-125-88ddfab
client docker - perconalab/pmm-client-fb:PR-125-88ddfab
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-125-88ddfab.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-125-46c2a91
client docker - perconalab/pmm-client-fb:PR-125-46c2a91
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-125-46c2a91.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-125-73b4703
client docker - perconalab/pmm-client-fb:PR-125-73b4703
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-125-73b4703.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server-packaging/pull/12 merged

**Pull request closed without merging**
