### PR TITLE
ci: upgrade v3 dependencies

### PR DESCRIPTION
**Pull request by ademidoff**
Sync the deps with the main branch

### CODE REVIEW

**Comment by JNKPercona** [comment]
Server docker: perconalab/pmm-server-fb:PR-3525-711ce0d
Client docker: perconalab/pmm-client-fb:PR-3525-711ce0d
Client tarball: https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3525-711ce0d.tar.gz
Staging instance: https://pmm.cd.percona.com/job/pmm3-aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3525-711ce0d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3525-711ce0d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed. Please check: https://pmm.cd.percona.com/job/pmm3-api-tests/137/

**Review by BupycHuk — APPROVED** [review]

**Comment by JNKPercona** [comment]
Server docker: perconalab/pmm-server-fb:PR-3525-b0b774a
Client docker: perconalab/pmm-client-fb:PR-3525-b0b774a
Client tarball: https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3525-b0b774a.tar.gz
Staging instance: https://pmm.cd.percona.com/job/pmm3-aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3525-b0b774a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm-client/pmm-client-PR-3525-b0b774a.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed. Please check: https://pmm.cd.percona.com/job/pmm3-api-tests/141/

**Pull request merged**
