### PR TITLE
PMM-4499 Grafana plugin Breadcrumb

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-376-730eeff
client docker - perconalab/pmm-client-fb:PR-376-730eeff
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-376-730eeff.tar.gz

**Comment by rnovikovP** [comment]
@adivinho I've just played with this  FB  and  LGTM

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-376-dccf338
client docker - perconalab/pmm-client-fb:PR-376-dccf338
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-376-dccf338.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/414 merged

**Pull request closed without merging**
