### PR TITLE
PMM-3851 Single sparkline v.2

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-235-ea7a2f1
client docker - perconalab/pmm-client-fb:PR-235-ea7a2f1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-235-ea7a2f1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-235-ea7a2f1
client docker - perconalab/pmm-client-fb:PR-235-ea7a2f1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-235-ea7a2f1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-235-ea7a2f1
client docker - perconalab/pmm-client-fb:PR-235-ea7a2f1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-235-ea7a2f1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-235-c536a28
client docker - perconalab/pmm-client-fb:PR-235-c536a28
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-235-c536a28.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-235-c536a28
client docker - perconalab/pmm-client-fb:PR-235-c536a28
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-235-c536a28.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/qan-app/pull/212 merged

**Pull request closed without merging**
