### PR TITLE
PMM-7723 Update grafana_dashboards branching and guideline

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Review by nikita-b — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1943-9288969
client docker - perconalab/pmm-client-fb:PR-1943-9288969
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1943-9288969.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1943-9288969&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1943-9288969.tar.gz

**Review by nikita-b — CHANGES_REQUESTED** [review]
Two questions:
1. I don't see a branch with this name on grafana-dashboard repo.
2. What's with PMM 1.0 version branch?

**Comment by adivinho** [comment]
> 1. I don't see a branch with this name on grafana-dashboard repo.
PMM-2.0 branch will be renamed to main as soon as this PR is merged

> 2. What's with PMM 1.0 version branch?
PMM-1.0 will stay as master branch
@denisok Please confirm.

**Comment by denisok** [comment]
we will rename PMM-2.0 to `main` and it will be default.
`master` just will stay as is.

**Review by denisok — APPROVED** [review]

**Review by nikita-b — APPROVED** [review]

**Review by nikita-b — APPROVED** [review]

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7633/

**Pull request merged**
