### PR TITLE
PMM-7570 Custom password for /metrics.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1928-894c602
client docker - perconalab/pmm-client-fb:PR-1928-894c602
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-894c602.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1928-894c602&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-894c602.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7553/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1928-ca0ffbf
client docker - perconalab/pmm-client-fb:PR-1928-ca0ffbf
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-ca0ffbf.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1928-ca0ffbf&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-ca0ffbf.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/7012/

**Comment by JiriCtvrtka** [comment]
Testsuite failed on check results https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-testsuite/detail/pmm2-testsuite/7012/pipeline everything else was green.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1928-bd8f751
client docker - perconalab/pmm-client-fb:PR-1928-bd8f751
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-bd8f751.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1928-bd8f751&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-bd8f751.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7589/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1928-a0ff220
client docker - perconalab/pmm-client-fb:PR-1928-a0ff220
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-a0ff220.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1928-a0ff220&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1928-a0ff220.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7591/

**Pull request closed without merging**
