### PR TITLE
SAAS-243 Update platform auth API

### PR DESCRIPTION
**Pull request by artemgavrilov**
https://jira.percona.com/browse/SAAS-243

- [ ] https://github.com/percona/pmm-managed/pull/438

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1035-d047874
client docker - perconalab/pmm-client-fb:PR-1035-d047874
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1035-d047874.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1035-d047874
client docker - perconalab/pmm-client-fb:PR-1035-d047874
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1035-d047874.tar.gz

**Comment by artemgavrilov** [comment]
Requires percona-platform/authed#30 on dev for passing tests.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1035-4d4c658
client docker - perconalab/pmm-client-fb:PR-1035-4d4c658
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1035-4d4c658.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1035-a796800
client docker - perconalab/pmm-client-fb:PR-1035-a796800
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1035-a796800.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1035-fa60652
client docker - perconalab/pmm-client-fb:PR-1035-fa60652
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1035-fa60652.tar.gz

**Pull request closed without merging**
