### PR TITLE
PMM-2610 configure grafana snapshot timeout

### PR DESCRIPTION
**Pull request by delgod**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-53-92c0c12
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-53-92c0c12.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-53-e5970d2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-53-e5970d2.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-53-ca21a31
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-53-ca21a31.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-53-d7af3c3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-53-d7af3c3.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server-packaging/pull/7  merged

**Pull request closed without merging**
