### PR TITLE
PMM-3072 Fix copy to clipboard button

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-3072

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-105-29734ad
client docker - perconalab/pmm-client-fb:PR-105-29734ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-105-29734ad.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-105-a33718d
client docker - perconalab/pmm-client-fb:PR-105-a33718d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-105-a33718d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-105-db4bc14
client docker - perconalab/pmm-client-fb:PR-105-db4bc14
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-105-db4bc14.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/256 , https://github.com/percona/qan-app/pull/134 merged

**Pull request closed without merging**
