### PR TITLE
PMM-4518 use ansible playbooks from 'percona-images' repo

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-421-6f4dd66
client docker - perconalab/pmm-client-fb:PR-421-6f4dd66
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-421-6f4dd66.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-421-adbf0d3
client docker - perconalab/pmm-client-fb:PR-421-adbf0d3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-421-adbf0d3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-421-0764165
client docker - perconalab/pmm-client-fb:PR-421-0764165
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-421-0764165.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-421-44505d2
client docker - perconalab/pmm-client-fb:PR-421-44505d2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-421-44505d2.tar.gz

**Comment by AlekSi** [comment]
Looks like all those things were merged. Please confirm and close/delete.

**Pull request closed without merging**
