### PR TITLE
PMM-3146 Add current build

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-3146

### CODE REVIEW

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server/pull/93  merged

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server/pull/93  merged

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-118-394e7ed
client docker - perconalab/pmm-client-fb:PR-118-394e7ed
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-118-394e7ed.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-server/pull/93  merged

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-118-394e7ed
client docker - perconalab/pmm-client-fb:PR-118-394e7ed
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-118-394e7ed.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-118-394e7ed
client docker - perconalab/pmm-client-fb:PR-118-394e7ed
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-118-394e7ed.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-118-394e7ed
client docker - perconalab/pmm-client-fb:PR-118-394e7ed
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-118-394e7ed.tar.gz

**Pull request closed without merging**
