### PR TITLE
SAAS-315 FB

### PR DESCRIPTION
**Pull request by palash25**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1160-35dcb1a
client docker - perconalab/pmm-client-fb:PR-1160-35dcb1a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1160-35dcb1a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1160-e3074cb
client docker - perconalab/pmm-client-fb:PR-1160-e3074cb
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1160-e3074cb.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4529/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3904/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5077/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4530/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3905/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5079/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1160-6695e7c
client docker - perconalab/pmm-client-fb:PR-1160-6695e7c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1160-6695e7c.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4534/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3909/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5088/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1160-4a127dc
client docker - perconalab/pmm-client-fb:PR-1160-4a127dc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1160-4a127dc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1160-4a127dc
client docker - perconalab/pmm-client-fb:PR-1160-4a127dc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1160-4a127dc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1160-4a127dc
client docker - perconalab/pmm-client-fb:PR-1160-4a127dc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1160-4a127dc.tar.gz

**Comment by AlekSi** [comment]
The next build there: https://github.com/Percona-Lab/pmm-submodules/pull/1174

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4579/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3961/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5159/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4580/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3962/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5160/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/4581/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/3963/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5161/

**Pull request closed without merging**
