### PR TITLE
PMM-4192 [FB] MongoDB Explain

### PR DESCRIPTION
**Pull request by percona-csalguero**
- [ ] https://github.com/percona/pmm/pull/420
- [ ] https://github.com/percona/pmm-managed/pull/362
- [ ] https://github.com/percona/pmm-agent/pull/109
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/85

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-7638760
client docker - perconalab/pmm-client-fb:PR-757-7638760
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-7638760.tar.gz

**Comment by AlekSi** [comment]
@percona-csalguero @BupycHuk API tests are not there

**Comment by BupycHuk** [comment]
@AlekSi I think we should create new issue for API tests for tests where we need pmm-agent.

**Comment by AlekSi** [comment]
https://github.com/Percona-Lab/pmm-api-tests/pull/85 is not added to .gitmodules

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-a517486
client docker - perconalab/pmm-client-fb:PR-757-a517486
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-a517486.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-9c283bc
client docker - perconalab/pmm-client-fb:PR-757-9c283bc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-9c283bc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-b692d0d
client docker - perconalab/pmm-client-fb:PR-757-b692d0d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-b692d0d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-74ac70c
client docker - perconalab/pmm-client-fb:PR-757-74ac70c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-74ac70c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-74ac70c
client docker - perconalab/pmm-client-fb:PR-757-74ac70c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-74ac70c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-74ac70c
client docker - perconalab/pmm-client-fb:PR-757-74ac70c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-74ac70c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-12a1e6e
client docker - perconalab/pmm-client-fb:PR-757-12a1e6e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-12a1e6e.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-ce7abb3
client docker - perconalab/pmm-client-fb:PR-757-ce7abb3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-ce7abb3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-a9d94b2
client docker - perconalab/pmm-client-fb:PR-757-a9d94b2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-a9d94b2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-757-2459696
client docker - perconalab/pmm-client-fb:PR-757-2459696
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-757-2459696.tar.gz

**Pull request closed without merging**
