### PR TITLE
PMM-7 upgrade go version

### PR DESCRIPTION
**Pull request by nikita-b**
Upgrade Go Lang to 1.18.3 (A couple of CVE were fixed).
Also, goreleaser was upgraded to 1.9.2. (We don't use checksum because we use package)

### CODE REVIEW

**Review by artemgavrilov — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2564-28970c0
client docker - perconalab/pmm-client-fb:PR-2564-28970c0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2564-28970c0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2564-28970c0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2564-28970c0.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10273/

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/9797/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/16946/

**Comment by JNKPercona** [comment]
Dockerway Upgrade tests have failed, Please check: Upgrade: https://pmm.cd.percona.com/job/pmm2-upgrade-tests/15487/

**Pull request merged**
