### PR TITLE
PMM-5871 node exporter updated with upstream

### PR DESCRIPTION
**Pull request by tshcherban**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2215-0010e1e
client docker - perconalab/pmm-client-fb:PR-2215-0010e1e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2215-0010e1e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2215-0010e1e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2215-0010e1e.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/8823/

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/8282/

**Comment by puneet0191** [comment]
@tshcherban close this?

**Comment by tshcherban** [comment]
yep, obsolete

**Pull request closed without merging**
