### PR TITLE
PMM-7383 Backup location delete

### PR DESCRIPTION
**Pull request by Dasio**
[PMM-7383](https://jira.percona.com/browse/PMM-7383)

- [ ] Links to other linked pull requests (optional).
- PMM-managed - https://github.com/percona/pmm-managed/pull/666
- API - https://github.com/percona/pmm/pull/686
- API tests - https://github.com/Percona-Lab/pmm-api-tests/pull/192

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1507-cac1225
client docker - perconalab/pmm-client-fb:PR-1507-cac1225
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-cac1225.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1507-cac1225&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-cac1225.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5936/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5353/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6892/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1507-2d417f7
client docker - perconalab/pmm-client-fb:PR-1507-2d417f7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-2d417f7.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1507-2d417f7&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-2d417f7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1507-2d417f7
client docker - perconalab/pmm-client-fb:PR-1507-2d417f7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-2d417f7.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1507-2d417f7&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-2d417f7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1507-2d417f7
client docker - perconalab/pmm-client-fb:PR-1507-2d417f7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-2d417f7.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1507-2d417f7&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-2d417f7.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5977/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5394/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6943/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5974/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5391/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6940/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5979/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5396/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/6945/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1507-a0de394
client docker - perconalab/pmm-client-fb:PR-1507-a0de394
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-a0de394.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1507-a0de394&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1507-a0de394.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6037/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5454/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7023/

**Comment by yurkovychv** [comment]
Please ignore failed UI tests. 2 failed tests are not related to this FB. Fixing those right now

**Pull request closed without merging**
