### PR TITLE
PMM-3088 Fix downgrade case

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-3088

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-108-d846ff1
client docker - perconalab/pmm-client-fb:PR-108-d846ff1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-108-d846ff1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-108-ed3eaf3
client docker - perconalab/pmm-client-fb:PR-108-ed3eaf3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-108-ed3eaf3.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-108-b004e78
client docker - perconalab/pmm-client-fb:PR-108-b004e78
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-108-b004e78.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/254 merged

**Pull request closed without merging**
