### PR TITLE
PMM-8725 DBaaS: fix paused state handling for Mysql Operator 1.9.0

### PR DESCRIPTION
**Pull request by jprukner**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2022-3fcf619
client docker - perconalab/pmm-client-fb:PR-2022-3fcf619
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2022-3fcf619.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2022-3fcf619&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2022-3fcf619.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7941/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/9937/

**Comment by jprukner** [comment]
failed API tests are not related to the fix

**Pull request closed without merging**
