### PR TITLE
PMM-10600: Update version of mongodb exporter

### PR DESCRIPTION
**Pull request by dliakhov**
[PMM-10600](https://jira.percona.com/browse/PMM-10600) Include new version of mongodb_exporter to PMM to track new MongoDB vendor and version information

- [ ] Links to other linked pull requests.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2872-d186d7d
client docker - perconalab/pmm-client-fb:PR-2872-d186d7d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2872-d186d7d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2872-d186d7d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2872-d186d7d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/11696/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2872-d186d7d
client docker - perconalab/pmm-client-fb:PR-2872-d186d7d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2872-d186d7d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2872-d186d7d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2872-d186d7d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/11698/

**Review by floatinginbits — APPROVED** [review]

**Review by denisok — APPROVED** [review]

**Pull request merged**
