### PR TITLE
PMM-3911 Simplify slowlog agent status handling.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by AlekSi** [comment]
https://github.com/percona/pmm-agent/pull/40

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-250-54bcf19
client docker - perconalab/pmm-client-fb:PR-250-54bcf19
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-250-54bcf19.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-250-d4332fa
client docker - perconalab/pmm-client-fb:PR-250-d4332fa
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-250-d4332fa.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-250-0c75413
client docker - perconalab/pmm-client-fb:PR-250-0c75413
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-250-0c75413.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-250-f5bc735
client docker - perconalab/pmm-client-fb:PR-250-f5bc735
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-250-f5bc735.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-250-574274c
client docker - perconalab/pmm-client-fb:PR-250-574274c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-250-574274c.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-agent/pull/40 merged

**Pull request closed without merging**
