### PR TITLE
PMM-5684 Information_schema cache disable

### PR DESCRIPTION
**Pull request by JiriCtvrtka**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1011-35f6b6e
client docker - perconalab/pmm-client-fb:PR-1011-35f6b6e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1011-35f6b6e.tar.gz

**Comment by BupycHuk** [comment]
@puneet0191 could you take a look, please? Looks like tests are failing because of changes in this PR.

**Comment by puneet0191** [comment]
@BupycHuk @JiriCtvrtka checking with FB again on UI test job

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1011-5a2fa80
client docker - perconalab/pmm-client-fb:PR-1011-5a2fa80
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1011-5a2fa80.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1011-32fd006
client docker - perconalab/pmm-client-fb:PR-1011-32fd006
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1011-32fd006.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1011-8033754
client docker - perconalab/pmm-client-fb:PR-1011-8033754
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1011-8033754.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1011-a7fd6fc
client docker - perconalab/pmm-client-fb:PR-1011-a7fd6fc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1011-a7fd6fc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1011-ad41a2e
client docker - perconalab/pmm-client-fb:PR-1011-ad41a2e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1011-ad41a2e.tar.gz

**Pull request closed without merging**
