### PR TITLE
PMM-3302 clickhouse monitoring inside pmm server

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-140-a4f63a2
client docker - perconalab/pmm-client-fb:PR-140-a4f63a2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-140-a4f63a2.tar.gz

**Comment by AlekSi** [comment]
@adivinho Please merge it once FB is tested.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-140-c4ef30f
client docker - perconalab/pmm-client-fb:PR-140-c4ef30f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-140-c4ef30f.tar.gz

**Comment by adivinho** [comment]
It has been prepared the correct pull request
https://github.com/Percona-Lab/pmm-submodules/pull/141

**Pull request closed without merging**
