### PR TITLE
PMM-6877 [FB] MongoS recongnition

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1890-45f6159
client docker - perconalab/pmm-client-fb:PR-1890-45f6159
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1890-45f6159.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1890-45f6159&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1890-45f6159.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7371/

**Comment by aslamkhan-dremio** [comment]
@percona-csalguero - Is this going to fix below issue? we want replsetgetstatus as well?

`msg="cannot get replSetGetStatus: replSetGetStatus is not supported through mongos"`

**Comment by denisok** [comment]
@aslamkhan-dremio  yes: https://github.com/percona/mongodb_exporter/commit/36864a012622c472298ee87ba62c6cd8b62af562

**Pull request closed without merging**
