### PR TITLE
PMM-9398 Error for InnoDB Log Buffer Usage metric dashboard FB

### PR DESCRIPTION
**Pull request by cezmunsta**
https://jira.percona.com/browse/PMM-9398

- https://github.com/percona/grafana-dashboards/pull/1369

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2672-b59c8b8
client docker - perconalab/pmm-client-fb:PR-2672-b59c8b8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2672-b59c8b8.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2672-b59c8b8&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2672-b59c8b8.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10785/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2672-3a6e91d
client docker - perconalab/pmm-client-fb:PR-2672-3a6e91d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2672-3a6e91d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2672-3a6e91d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2672-3a6e91d.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10805/

**Comment by ErikaDoniecova** [comment]
There are no new tests failing. https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/824/pipeline

**Pull request closed without merging**
