### PR TITLE
PMM-7448: FB

### PR DESCRIPTION
**Pull request by oter**
https://jira.percona.com/browse/PMM-7448

https://github.com/percona/pmm/pull/683
https://github.com/percona/pmm-managed/pull/665

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-73f9623
client docker - perconalab/pmm-client-fb:PR-1553-73f9623
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-73f9623.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-73f9623&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-73f9623.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6150/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5567/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7169/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-66247d0
client docker - perconalab/pmm-client-fb:PR-1553-66247d0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-66247d0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-66247d0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-66247d0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-fff20d7
client docker - perconalab/pmm-client-fb:PR-1553-fff20d7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-fff20d7.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-fff20d7&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-fff20d7.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6243/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5653/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7279/

**Comment by puneet0191** [comment]
The UI tests fail on this because this is an outdated FB, please rewind it with latest changes on release/2.16 branch @oter

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-650f6a9
client docker - perconalab/pmm-client-fb:PR-1553-650f6a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-650f6a9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-650f6a9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-650f6a9.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-084ca72
client docker - perconalab/pmm-client-fb:PR-1553-084ca72
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-084ca72.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-084ca72&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-084ca72.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7383/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-09fd812
client docker - perconalab/pmm-client-fb:PR-1553-09fd812
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-09fd812.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-09fd812&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-09fd812.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6347/

**Comment by oter** [comment]
> API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6347/

failed tests are not related to my changes.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-355c761
client docker - perconalab/pmm-client-fb:PR-1553-355c761
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-355c761.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-355c761&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-355c761.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6369/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1553-f923a80
client docker - perconalab/pmm-client-fb:PR-1553-f923a80
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-f923a80.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1553-f923a80&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1553-f923a80.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6376/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7425/

**Pull request closed without merging**
