### PR TITLE
PMM-6017 merge pmm-server-packaging to pmm-server

### PR DESCRIPTION
**Pull request by atymchuk**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1590-7e30e48
client docker - perconalab/pmm-client-fb:PR-1590-7e30e48
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1590-7e30e48.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1590-7e30e48&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1590-7e30e48.tar.gz

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7326/

**Review by BupycHuk — APPROVED** [review]

**Comment by puneet0191** [comment]
please create separate PR, without submodules, I will run the UI tests with FB tag, seems like some issue with test code, probably need to use release/2.16 test code on this FB.

**Comment by atymchuk** [comment]
closing this, since it's outdated

**Pull request closed without merging**
