### PR TITLE
PMM-3019 rootless image

### PR DESCRIPTION
**Pull request by selamanse**
https://jira.percona.com/browse/PMM-3019

trying to create a rootless image

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2749-d8b8921
client docker - perconalab/pmm-client-fb:PR-2749-d8b8921
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2749-d8b8921.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2749-d8b8921&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2749-d8b8921.tar.gz

**Comment by JNKPercona** [comment]
pmm2-client testsuite has failed, Please check: BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/10680/

**Comment by ademidoff** [comment]
@selamanse Could you please rebase you branch on PMM-2.0? There was a bug that hung the pipeline.

**Comment by ademidoff** [comment]
You can trigger the build with `make trigger` :)

**Comment by selamanse** [comment]
@atymchuk I think the rebase did not help? can you check the pipeline for me please?

**Pull request closed without merging**
