### PR TITLE
PMM-2637 update improvements

### PR DESCRIPTION
**Pull request by delgod**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-3095318
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-3095318.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-8764ae9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-8764ae9.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-5570b79
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-5570b79.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-99a1923
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-99a1923.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-6375115
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-6375115.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-c262f0c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-c262f0c.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-59-2a44477
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-59-2a44477.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/pmm-manage/pull/16
https://github.com/percona/grafana-dashboards/pull/208
merged

**Pull request closed without merging**
