### PR TITLE
add helm-tests workflow status report

### PR DESCRIPTION
**Pull request by denisok**
https://jira.percona.com/browse/PMM-985

- [ ] https://github.com/Percona-Lab/jenkins-pipelines/pull/1601

### CODE REVIEW

**Comment by denisok** [comment]
@puneet0191 see action result in check statuses

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2604-80c3f58
client docker - perconalab/pmm-client-fb:PR-2604-80c3f58
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2604-80c3f58.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2604-80c3f58&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2604-80c3f58.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10459/

**Comment by puneet0191** [comment]
thank you, this helps us move into using GitHub actions with our current Jenkins submodule build job, awesome!

**Review by puneet0191 — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2604-0478f5c
client docker - perconalab/pmm-client-fb:PR-2604-0478f5c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2604-0478f5c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2604-0478f5c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2604-0478f5c.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10462/

**Pull request merged**
