### PR TITLE
PMM-9729 Update golang version

### PR DESCRIPTION
**Pull request by artemgavrilov**
https://jira.percona.com/browse/PMM-9729

- [ ] Links to other linked pull requests.

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2464-368ae34
client docker - perconalab/pmm-client-fb:PR-2464-368ae34
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2464-368ae34.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2464-368ae34&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2464-368ae34.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9745/

**Comment by artemgavrilov** [comment]
API tests failure is unrelated.

**Review by nikita-b — APPROVED** [review]

**Comment by nikita-b** [comment]
@artemgavrilov We'll need to rebuild image with prepare-rpmbuild-docker-ecr job (In Jenkins)

**Comment by artemgavrilov** [comment]
> @artemgavrilov We'll need to rebuild image with prepare-rpmbuild-docker-ecr job (In Jenkins)

Yep, and I guess I need your help with that.

**Pull request merged**
