### PR TITLE
PMM-2330: Annotations.

### PR DESCRIPTION
**Pull request by arvenil**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-21-11f68b5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-21-11f68b5.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-21-0414b2b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-21-0414b2b.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-21-e8b799d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-21-e8b799d.tar.gz

**Comment by rnovikovP** [comment]
All branches are merged to master

**Pull request closed without merging**
