### PR TITLE
PMM-13317 Remove clickhouse exporter

### PR DESCRIPTION
**Pull request by ademidoff**
https://jira.percona.com/browse/PMM-13317

- https://github.com/percona/pmm/pull/3168

TODO before merging:
* restore ci.yml 🟢

### CODE REVIEW

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/3168

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3697-ad9ad73
client docker - perconalab/pmm-client-fb:PR-3697-ad9ad73
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3697-ad9ad73.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3697-ad9ad73&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3697-ad9ad73.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3697-49f0766
client docker - perconalab/pmm-client-fb:PR-3697-49f0766
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3697-49f0766.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3697-49f0766&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3697-49f0766.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/15360/

**Review by talhabinrizwan — APPROVED** [review]

**Pull request merged**
