### PR TITLE
PMM-6909 Templates API

### PR DESCRIPTION
**Pull request by artemgavrilov**
https://jira.percona.com/browse/PMM-6909

- [ ] https://github.com/percona/pmm-managed/pull/541
- [ ] https://github.com/Percona-Lab/pmm-api-tests/pull/147

To enable this API provide env variable `PERCONA_TEST_IA=true`

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1271-6b4fc69
client docker - perconalab/pmm-client-fb:PR-1271-6b4fc69
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-6b4fc69.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1271-6b4fc69&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-6b4fc69.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5078/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4462/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5789/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1271-65e0729
client docker - perconalab/pmm-client-fb:PR-1271-65e0729
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-65e0729.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1271-65e0729&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-65e0729.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/5082/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/4466/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/5796/

**Comment by AlekSi** [comment]
Let's see if Jenkins will work now…

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1271-986444f
client docker - perconalab/pmm-client-fb:PR-1271-986444f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-986444f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1271-986444f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-986444f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1271-078c531
client docker - perconalab/pmm-client-fb:PR-1271-078c531
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-078c531.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1271-078c531&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-078c531.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1271-e0befe4
client docker - perconalab/pmm-client-fb:PR-1271-e0befe4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-e0befe4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1271-e0befe4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1271-e0befe4.tar.gz

**Pull request closed without merging**
