### PR TITLE
Release PMM 2.15.1 with mongodb_exporter 0.20.3

### PR DESCRIPTION
**Pull request by percona-csalguero**

### CODE REVIEW

**Review by denisok — APPROVED** [review]

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1605-a6d6edf
client docker - perconalab/pmm-client-fb:PR-1605-a6d6edf
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1605-a6d6edf.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1605-a6d6edf&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1605-a6d6edf.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6317/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7362/

**Comment by denisok** [comment]
UI test failures should be disregarded: https://github.com/Percona-Lab/pmm-submodules/pull/1594#issuecomment-796364928

**Review by rnovikovP — APPROVED** [review]

**Comment by denisok** [comment]
checked with Nurlan, we can merge it now.

**Pull request merged**
