### PR TITLE
PMM-10231 Credentials source bugfix

### PR DESCRIPTION
**Pull request by tshcherban**
https://jira.percona.com/browse/PMM-10231

- [pmm#990](https://github.com/percona/pmm/pull/990)

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2609-4d0c767
client docker - perconalab/pmm-client-fb:PR-2609-4d0c767
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-4d0c767.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2609-4d0c767&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-4d0c767.tar.gz

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/990

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2609-200ee05
client docker - perconalab/pmm-client-fb:PR-2609-200ee05
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-200ee05.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2609-200ee05&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-200ee05.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10493/

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10493/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2609-200ee05
client docker - perconalab/pmm-client-fb:PR-2609-200ee05
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-200ee05.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2609-200ee05&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-200ee05.tar.gz

**Comment by igor-cherkasov** [comment]
Tested on clients:

- https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2609-200ee05.tar.gz
- https://downloads.percona.com/downloads/pmm2/2.28.0/binary/tarball/pmm2-client-2.28.0.tar.gz

I confirm that `credentials-source` and `defaults-file` are not listed in output of `pmm-admin` comman

Snag_2649b26
Snag_264a547
d

**Comment by igor-cherkasov** [comment]
Subcommands are also don't contain `credentials-source` and `defaults-file` flags:
image
image

**Pull request closed without merging**
