### PR TITLE
PMM-1274: Export PMM Logs

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-12-1aedd09
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-12-1aedd09.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-12-1aedd09
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-12-1aedd09.tar.gz

**Comment by JNKPercona** [comment]
docker - perconalab/pmm-server-fb:PR-12-d3ad845
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-12-d3ad845.tar.gz

**Comment by AlekSi** [comment]
Merged into master.

**Pull request closed without merging**
