### PR TITLE
PMM-4127 restored missed vmstat metrics

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-284-f879e1c
client docker - perconalab/pmm-client-fb:PR-284-f879e1c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-284-f879e1c.tar.gz

**Comment by rnovikovP** [comment]
but looks like  https://github.com/percona/pmm-managed/pull/200  already merged. do we need this FB ?

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-284-f879e1c
client docker - perconalab/pmm-client-fb:PR-284-f879e1c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-284-f879e1c.tar.gz

**Comment by adivinho** [comment]
> but looks like [percona/pmm-managed#200](https://github.com/percona/pmm-managed/pull/200) already merged. do we need this FB ?

You referred to the PR for netstat metrics but this one is for vmstat

**Pull request closed without merging**
