### PR TITLE
PMM-11272 Advisors

### PR DESCRIPTION
**Pull request by artemgavrilov**
https://jira.percona.com/browse/PMM-11272

- [ ] https://github.com/percona/pmm/pull/1684
- [x] https://github.com/percona-platform/saas/pull/67

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3068-9a7041d
client docker - perconalab/pmm-client-fb:PR-3068-9a7041d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3068-9a7041d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3068-9a7041d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3068-9a7041d.tar.gz

**Comment by JNKPercona** [comment]
Looks like there are outdated source branches.
 Please update them and restart the job
 https://github.com/percona/pmm/pull/1684

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3068-eaac23e
client docker - perconalab/pmm-client-fb:PR-3068-eaac23e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3068-eaac23e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3068-eaac23e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3068-eaac23e.tar.gz

**Comment by VoK0** [comment]
FB : https://github.com/Percona-Lab/pmm-submodules/pull/3068#issuecomment-1437036440 tested Phase 1 - Verify that 2.36.0 version of PMM-Server is working properly  with new Advisors BE

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-3068-f8e0fe5
client docker - perconalab/pmm-client-fb:PR-3068-f8e0fe5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3068-f8e0fe5.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3068-f8e0fe5&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3068-f8e0fe5.tar.gz

**Comment by artemgavrilov** [comment]
Use this instead: https://github.com/Percona-Lab/pmm-submodules/pull/3077

**Pull request closed without merging**
