### PR TITLE
PMM-5524 API test for prometheus reload.

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-22b0a32
client docker - perconalab/pmm-client-fb:PR-879-22b0a32
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-22b0a32.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-22b0a32
client docker - perconalab/pmm-client-fb:PR-879-22b0a32
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-22b0a32.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-cc5b8d8
client docker - perconalab/pmm-client-fb:PR-879-cc5b8d8
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-cc5b8d8.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-f81193d
client docker - perconalab/pmm-client-fb:PR-879-f81193d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-f81193d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-136810a
client docker - perconalab/pmm-client-fb:PR-879-136810a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-136810a.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-89fa584
client docker - perconalab/pmm-client-fb:PR-879-89fa584
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-89fa584.tar.gz

**Comment by AlekSi** [comment]
@askomorokhov https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-api-tests/detail/pmm2-api-tests/3196/tests

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-3237add
client docker - perconalab/pmm-client-fb:PR-879-3237add
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-3237add.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-db5e8a7
client docker - perconalab/pmm-client-fb:PR-879-db5e8a7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-db5e8a7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-db5e8a7
client docker - perconalab/pmm-client-fb:PR-879-db5e8a7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-db5e8a7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-417196f
client docker - perconalab/pmm-client-fb:PR-879-417196f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-417196f.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-e9a9cec
client docker - perconalab/pmm-client-fb:PR-879-e9a9cec
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-e9a9cec.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-0c3af37
client docker - perconalab/pmm-client-fb:PR-879-0c3af37
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-0c3af37.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-879-bc222d6
client docker - perconalab/pmm-client-fb:PR-879-bc222d6
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-879-bc222d6.tar.gz

**Pull request closed without merging**
