### PR TITLE
PMM-5563 Annotation service, node.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-7a6100c
client docker - perconalab/pmm-client-fb:PR-895-7a6100c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-7a6100c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-728ef9c
client docker - perconalab/pmm-client-fb:PR-895-728ef9c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-728ef9c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-4f81f73
client docker - perconalab/pmm-client-fb:PR-895-4f81f73
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-4f81f73.tar.gz

**Comment by BupycHuk** [comment]
@JiriCtvrtka please rewind submodules.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-2fc6ba2
client docker - perconalab/pmm-client-fb:PR-895-2fc6ba2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-2fc6ba2.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-b7c0240
client docker - perconalab/pmm-client-fb:PR-895-b7c0240
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-b7c0240.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-db49ce5
client docker - perconalab/pmm-client-fb:PR-895-db49ce5
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-db49ce5.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-457e180
client docker - perconalab/pmm-client-fb:PR-895-457e180
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-457e180.tar.gz

**Comment by BupycHuk** [comment]
He didn't have access to push to percona-lab, that's why PR was done from his fork instead of branch. We are trying to fix this issue with IT team

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-895-0ec6d3e
client docker - perconalab/pmm-client-fb:PR-895-0ec6d3e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-895-0ec6d3e.tar.gz

**Pull request closed without merging**
