### PR TITLE
PMM-3061 Agentless PostgreSQL and MySQL (Second try)

### PR DESCRIPTION
**Pull request by darly-s**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-120-e154aa0
client docker - perconalab/pmm-client-fb:PR-120-e154aa0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-120-e154aa0.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-120-c2e8331
client docker - perconalab/pmm-client-fb:PR-120-c2e8331
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-120-c2e8331.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-120-b9c05d1
client docker - perconalab/pmm-client-fb:PR-120-b9c05d1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-120-b9c05d1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-120-8aa5d46
client docker - perconalab/pmm-client-fb:PR-120-8aa5d46
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-120-8aa5d46.tar.gz

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/262
https://github.com/percona/qan-app/pull/137  merged

**Pull request closed without merging**
