### PR TITLE
PMM-7375

### PR DESCRIPTION
**Pull request by fabio-silva**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1557-c1aec0d
client docker - perconalab/pmm-client-fb:PR-1557-c1aec0d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-c1aec0d.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1557-c1aec0d&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-c1aec0d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1557-17757cc
client docker - perconalab/pmm-client-fb:PR-1557-17757cc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-17757cc.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1557-17757cc&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-17757cc.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1557-17757cc
client docker - perconalab/pmm-client-fb:PR-1557-17757cc
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-17757cc.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1557-17757cc&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-17757cc.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6177/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5594/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7208/

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6176/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5593/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7207/

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1557-e9b929a
client docker - perconalab/pmm-client-fb:PR-1557-e9b929a
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-e9b929a.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1557-e9b929a&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-e9b929a.tar.gz

**Comment by JNKPercona** [comment]
Some Tests have Failed Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/6179/ BATS: https://pmm.cd.percona.com/job/pmm2-testsuite/5596/ & UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/7211/

**Comment by Dasio** [comment]
Failed API tests can be ignored inventory.TestExternalService. Not related to this. It's already open PR for it. https://github.com/Percona-Lab/pmm-api-tests/pull/191

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1557-0ffa7dd
client docker - perconalab/pmm-client-fb:PR-1557-0ffa7dd
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-0ffa7dd.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1557-0ffa7dd&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-0ffa7dd.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-1557-10514f9
client docker - perconalab/pmm-client-fb:PR-1557-10514f9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-10514f9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1557-10514f9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1557-10514f9.tar.gz

**Pull request closed without merging**
