### PR TITLE
PMM-3705 build pmm-managed with make release

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-270-988ffa1
client docker - perconalab/pmm-client-fb:PR-270-988ffa1
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-270-988ffa1.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-270-bf44147
client docker - perconalab/pmm-client-fb:PR-270-bf44147
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-270-bf44147.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-270-6e8243e
client docker - perconalab/pmm-client-fb:PR-270-6e8243e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-270-6e8243e.tar.gz

**Comment by AlekSi** [comment]
Is it a duplicate? Please close and delete branch if it is.

**Pull request closed without merging**
