### PR TITLE
Fix error updating percona-release package

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-143-d85fe95
client docker - perconalab/pmm-client-fb:PR-143-d85fe95
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-143-d85fe95.tar.gz

**Comment by rnovikovP** [comment]
@adivinho  can/should we also apply this fix to 2.0 branch?

**Comment by EvgeniyPatlan** [comment]
@rnovikovP yes it is good idea to use latest package for all branches

**Comment by adivinho** [comment]
> @adivinho can/should we also apply this fix to 2.0 branch?

#144

**Pull request merged**
