### PR TITLE
PMM-2860 PMM-2905 Improve diagnostics for support.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-cdb2431
client docker - perconalab/pmm-client-fb:PR-98-cdb2431
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-cdb2431.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-9c6018c
client docker - perconalab/pmm-client-fb:PR-98-9c6018c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-9c6018c.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-9c6018c
client docker - perconalab/pmm-client-fb:PR-98-9c6018c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-9c6018c.tar.gz

**Comment by puneet0191** [comment]
@AlekSi please fix the conflicting files here

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-0ca0a11
client docker - perconalab/pmm-client-fb:PR-98-0ca0a11
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-0ca0a11.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-0ca0a11
client docker - perconalab/pmm-client-fb:PR-98-0ca0a11
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-0ca0a11.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-eedeb0d
client docker - perconalab/pmm-client-fb:PR-98-eedeb0d
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-eedeb0d.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-539280b
client docker - perconalab/pmm-client-fb:PR-98-539280b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-539280b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-98-fa84420
client docker - perconalab/pmm-client-fb:PR-98-fa84420
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm-client/pmm-client-PR-98-fa84420.tar.gz

**Comment by AlekSi** [comment]
Merged!

**Pull request closed without merging**
