### PR TITLE
PMM-10867 dummy build

### PR DESCRIPTION
**Pull request by ghost**
https://jira.percona.com/browse/PMM-10867

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2900-62f558f
client docker - perconalab/pmm-client-fb:PR-2900-62f558f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2900-62f558f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2900-62f558f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2900-62f558f.tar.gz

**Comment by ademidoff** [comment]
wow, nice PR title! Looks scary :)

**Comment by ghost** [comment]
Yesterday was a lucky day for ticket/PR IDs :)
I got PMM-11110 as well :)

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2900-62f558f
client docker - perconalab/pmm-client-fb:PR-2900-62f558f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2900-62f558f.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2900-62f558f&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2900-62f558f.tar.gz

**Pull request closed without merging**
