### PR TITLE
PMM-3424 New MongoDB driver.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-306-ca54b12
client docker - perconalab/pmm-client-fb:PR-306-ca54b12
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-306-ca54b12.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-306-ab7ca9e
client docker - perconalab/pmm-client-fb:PR-306-ab7ca9e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-306-ab7ca9e.tar.gz

**Comment by AlekSi** [comment]
@Nailya Could you please lightly test MongoDB metrics and queries with server and client from this PR? Everything should work as before (or better 😄).

**Comment by Nailya** [comment]
@AlekSi sure!

**Comment by Nailya** [comment]
@aleksi Mongodb metrics looks ok, but there is a problem with QAN, if only MongoDB is added QAN fails with JS error and no data is displayed.  And there is "Failed to get replSet status: cannot decode timestamp into a time.Time" in pmm-agent logs for MongoDB replicaset. 
I've  checked the same with master build and everything works ok.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-306-cfe9cf7
client docker - perconalab/pmm-client-fb:PR-306-cfe9cf7
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-306-cfe9cf7.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-306-4d101ad
client docker - perconalab/pmm-client-fb:PR-306-4d101ad
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-306-4d101ad.tar.gz

**Comment by DexterHD** [comment]
@AlekSi @Nailya 

> And there is "Failed to get replSet status: cannot decode timestamp into a time.Time" in pmm-agent logs for MongoDB replicaset.

Fixed in [this commit](https://github.com/percona/mongodb_exporter/pull/141/commits/259cc896c129423e7f77ca276d6abadca88040e4). Regression test also has added. [Successfully built](https://travis-ci.com/percona/mongodb_exporter/builds/116619660) by TravisCI.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-306-294f92b
client docker - perconalab/pmm-client-fb:PR-306-294f92b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-306-294f92b.tar.gz

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-306-754835f
client docker - perconalab/pmm-client-fb:PR-306-754835f
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/pmm2-client/pmm2-client-PR-306-754835f.tar.gz

**Comment by AlekSi** [comment]
All branches were merged.

**Pull request closed without merging**
