### PR TITLE
PMM-4466 add grafana migrator

### PR DESCRIPTION
**Pull request by denisok**
https://jira.percona.com/browse/PMM-4466

pmm-update: https://github.com/percona/pmm-update/pull/157
pmm-server: https://github.com/percona/pmm-server/pull/314
jenkins-pipeline: https://github.com/Percona-Lab/jenkins-pipelines/pull/1272

### CODE REVIEW

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2401-64c48a4
client docker - perconalab/pmm-client-fb:PR-2401-64c48a4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2401-64c48a4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2401-64c48a4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2401-64c48a4.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9499/

**Comment by JNKPercona** [comment]
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/13138/

**Comment by nikita-b** [comment]
Heh, it seems we don't use build/bin/build-server in Jenkins at all.

**Review by nikita-b — APPROVED** [review]

**Comment by denisok** [comment]
> Heh, it seems we don't use build/bin/build-server in Jenkins at all.

I was surprised myself that we have double code.

**Comment by JNKPercona** [comment]
server docker - perconalab/pmm-server-fb:PR-2401-64c48a4
client docker - perconalab/pmm-client-fb:PR-2401-64c48a4
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2401-64c48a4.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2401-64c48a4&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2401-64c48a4.tar.gz

**Comment by JNKPercona** [comment]
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/9518/

**Comment by denisok** [comment]
@nikita-b the API failure is known one: https://jira.percona.com/browse/PMM-9731

**Review by BupycHuk — APPROVED** [review]

**Comment by denisok** [comment]
@nikita-b please land, test fail is known.

**Pull request merged**
